### ISSUE TITLE
Dangerous DB update

### ISSUE THREAD

**Issue by znat** [botfront/botfront#100]
https://github.com/botfront/botfront/blob/80abbadcf2d8f048511a1c74ac0c4202c29805b4/botfront/imports/api/instances/instances.methods.js#L211

Missed that in the PR review but updating a whole collection without a selector is a major risk.

**Comment by pheel** [comment]
https://github.com/botfront/botfront/commit/2c982cb7fe445dd4e841c2686cee28b0c3bd4f73#r34240109
