### ISSUE TITLE
Botfront Platform Integration in CRM

### ISSUE THREAD

**Issue by nytrotechdev** [botfront/botfront#1002]
I have a CRM where, I need to integrate the Botfront platform, not Chatbot, each client/customer can create his own chatbot just like we do in Botfront. I tried to achieve it by putting the Botfront link in an iframe but it is not the optimal way.

Any suggestions or recommendations regarding my query or any other platform that might help me in my case is appreciated.

**Comment by brandaobrandisborges** [comment]
I can't help you achieve what you want, but I should wanr you that this may violate Rasa's [license terms](https://rasa.com/product/pricing/).
