### ISSUE TITLE
There is no box for try out chatbot!

### ISSUE THREAD

**Issue by Abu-Ishak** [botfront/botfront#1007]
Botfront doesn't show any box for sending messages.
![Screenshot (251)](https://user-images.githubusercontent.com/65851922/114294189-a5241080-9abe-11eb-94a6-9f9cebc8c00a.png)
any idea?

**Comment by nikirg** [comment]
Your rasa core server is insecure (HTTP), at the same time botfront URL have SSL.
In the browser console you can find the error: 
"Mixed Content : The page at '<URL>' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint '<URL>'. This request has been blocked; the content must be served over HTTPS."

**Comment by brandaobrandisborges** [comment]
I have faced this problem when my url's where wrong.
Go to `settings` and edit the urls on `credentials`, `instance` and `endpoint` to your host. I didn't need to change `http://botfront:3000/graphql` on `endpoint` though.

Also, ensure there is no firewall blocking your ports. I allow the following:
8000 duclking
5055 rasa action server
5005 rasa server
8888 botfront ui

Hope it helps.

**Comment by Abu-Ishak** [comment]
Thank you for your reply. It does work @brandaobrandisborges
