### ISSUE TITLE
More details in developer guide  

### ISSUE THREAD

**Issue by engahmed1190** [botfront/botfront#101]
> Can we have more details to the developer guide 

## Developing with Docker Compose

Until we provide a better way...

1. Set the `MODELS_LOCAL_PATH` environment variable in your shell with for example `export MODELS_LOCAL_PATH=~/botfront-projects/s`
2. Start Botfront locally with `meteor npm start`. Botfront will be available at [http://localhost:3000](http://localhost:3000)
3. In settings > endpoints: change domain names to `localhost`. Don't change ports
4. In settings > more settings > docker-compose change API host to `http://host.docker.internal:8080`

From step number **5** it doesn't make sense to me.

How I can get `botfront` command to run , I have also tried `npm install -g botfront` but failed to link locally running project 

![image](https://user-images.githubusercontent.com/25582838/60759438-e7850780-a025-11e9-833b-994e89e62462.png)

5. Create a Botfront projet with `botfront init`. Don't start it
6. In `.botfront/botfront.yml`,  set the `bf_project_id` with the project ID of the locally running Botfront
7. In `.botfront/botfront.yml`, set the `mongo_url` to `mongodb://host.docker.internal:3001/meteor`
8. Start the Botfront project with `botfront up`

Please add more details here .

**Comment by znat** [comment]
From your screenshot it seems you're not against the right db. Make sure you change the mongo_url var to localhost:3001/meteor

**Comment by engahmed1190** [comment]
@znat 

I have changed all the configuration to be `localhost `
**Credentials** 
![image](https://user-images.githubusercontent.com/25582838/60770342-502dbc00-a0da-11e9-9605-ddfddca54830.png)

**Endpoints** 
![image](https://user-images.githubusercontent.com/25582838/60770348-69cf0380-a0da-11e9-8036-d9640558e01f.png)

**Instance** 

![image](https://user-images.githubusercontent.com/25582838/60770353-81a68780-a0da-11e9-9b0c-ea6bdf848004.png)

But still have this error 

![image](https://user-images.githubusercontent.com/25582838/60770362-a6026400-a0da-11e9-8603-b401a966cf03.png)

**Comment by znat** [comment]
I meant in .botfront/botfront.yaml

Le dim. 7 juill. 2019 11 h 14, Ahmed Osama <notifications@github.com> a
écrit :

**Comment by engahmed1190** [comment]
Here is my .botfront/botfront.yaml 

`mongo_url` is setted to `mongodb://localhost:3001/meteor` .  what do you think might case this conflict 

I have check MongoDB and it's running on port 3001. 

![image](https://user-images.githubusercontent.com/25582838/60775738-7d07c080-a126-11e9-95e7-927fb1faaaaa.png)

**Comment by znat** [comment]
Hey @engahmed1190 have you checked the latest version? Works well for us

**Comment by engahmed1190** [comment]
Yeah. We can close it now
