### ISSUE TITLE
Training button is disabled

### ISSUE THREAD

**Issue by bsbarkur** [botfront/botfront#1012]
**Describe the bug**
I installed the latest botfront using npm install as indicated in the botfront documentation. And after issuing `botfront up`, I get taken to the botfront UI on the local machine on port 8888. However, the training after entering few utterances doesn't work. The botfront logs show have this trace:

```
botfront-rasa | 2021-04-15 04:42:48 DEBUG    rasa.utils.botfront  - Trying to fetch config from http://botfront:3000/graphql (retry #47577)
botfront-rasa | 2021-04-15 04:42:48 ERROR    sgqlc.endpoint.http  - GraphQL query failed with 1 errors
botfront-rasa | 2021-04-15 04:42:48 DEBUG    rasa.utils.botfront  - Cannot destructure property 'endpoints' of 'endpointsFetched' as it is null.
botfront-rasa | 2021-04-15 04:42:48 DEBUG    rasa.utils.botfront  - Trying to fetch config from http://botfront:3000/graphql (retry #47578)
botfront-rasa | 2021-04-15 04:42:48 ERROR    sgqlc.endpoint.http  - GraphQL query failed with 1 errors
botfront-rasa | 2021-04-15 04:42:48 DEBUG    rasa.utils.botfront  - Cannot destructure property 'endpoints' of 'endpointsFetched' as it is null.
```

Here are the docker containers that were loaded on my local system upon `botfront up` command.

```
$% docker ps
WARNING: unable to unmarshal config file /Users/b021B02185548554/.docker/config.json: unexpected end of JSON input
WARNING: Error loading config file: /Users/b021B02185548554/.docker/config.json: EOF
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS                                            NAMES
c34884ebeb9c        botfront/botfront:v1.0.5       "/docker/entrypoint.…"   10 minutes ago      Up 9 minutes        0.0.0.0:8888->3000/tcp                           botfront-app
477605a0e87d        botfront_demo_latest_actions   "./entrypoint.sh sta…"   10 minutes ago      Up 10 minutes       0.0.0.0:5055->5055/tcp                           botfront-actions
46fe2e42c156        botfront_demo_latest_rasa      "/bin/bash -o pipefa…"   10 minutes ago      Up 10 minutes       0.0.0.0:5005->5005/tcp                           botfront-rasa
71417a853a10        mongo:latest                   "docker-entrypoint.s…"   10 minutes ago      Up 10 minutes       0.0.0.0:27017->27017/tcp                         botfront-mongo
da7add569060        botfront/duckling:latest       "/bin/sh -c 'exec du…"   10 minutes ago      Up 10 minutes       0.0.0.0:8000->8000/tcp                           botfront-duckling
```

**Expected behavior**
Training should proceed upon logging to the Botfront UI upon entering few textual utterances. The training button remains disabled with the message saying the rasa instance is not reachable. It should be enabled.

**Desktop (please complete the following information):**
 - OS: Mac OS X 10.15.17
 - Browser: Chrome
 - Botfront version: 1.0.5

**Comment by igormfreitas** [comment]
Hi, bsbarkur.

You need to set the project-id for the training button to work.

Your problem looks like the one discussed in #909

**Comment by bsbarkur** [comment]
Setting project id in .botfront/botfront.yml worked. Although, this should be working by default no ? Thanks for the tips.

**Comment by brandaobrandisborges** [comment]
> Setting project id in .botfront/botfront.yml worked. Although, this should be working by default no ? Thanks for the tips.

Since you can have multiple bots, I think this is right. It's also refered in the documentation [here](https://botfront.io/docs/installation/local-machine):
![image](https://user-images.githubusercontent.com/51330067/115419775-f9bb4000-a1d0-11eb-953d-c8e4ac8f439b.png)
