### ISSUE TITLE
Training doesn't complete

### ISSUE THREAD

**Issue by bsbarkur** [botfront/botfront#1019]
So I have a simple dialog where I have a user utterance as "Hello" tagged with an intent. Then I created a bot response utterance as "Hi". And then hit the training button. I get this error:

```

botfront-app | 2021-04-20T06:16:28.465Z [error] : Training project wMeH3TnkYfGHcZWEr - 36208.07 ms user: 

HrPdpZNQ7HnuedSSA /imports/api/instances/instances.methods.js - rasa.train with {"projectId":"wMeH3TnkYfGHcZWEr"}    

error: Request failed with status code 500 at settle 

(/opt/bundle/bundle/programs/server/npm/node_modules/axios/lib/core/settle.js:17:12)

```

**Expected behavior**
Training should have been completed.

**Screenshots**
![image](https://user-images.githubusercontent.com/106684/115347876-9381ed80-a1cf-11eb-9ea2-7d30a5a3df8e.png)

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Browser Chrome

**Comment by brandaobrandisborges** [comment]
This is already refered [here](https://github.com/botfront/botfront/issues/986). Take a look in my solution. Hope it helps.
