### ISSUE TITLE
Provide the ability to write your own connector

### ISSUE THREAD

**Issue by amitbend** [botfront/botfront#117]
Many of us build bots for various platforms, and currently Botfront support only the webchat channel and working on a messenger channel.

I propose to provide developers the option to write their own connector to Botfront, and potentially opensource it. (as possible through Rasa)

**Comment by znat** [comment]
It's actually easy to do. You can implement your connector as a python package and build your own image from rasa-for-botfront and pip install your connector there

**Comment by znat** [comment]
done on master. Will be in 0.19
