### ISSUE TITLE
Path must be a string. Received undefined

### ISSUE THREAD

**Issue by engahmed1190** [botfront/botfront#145]
**Describe the bug**
Error when clicking on Train Everything 
**To Reproduce**
1. `meteor npm run start:docker-compose.dev`
2. Go to 'http://localhost:3000'
3. Click on 'Train Everything'

**Expected behavior**
Training to be accomplished and save new model files.

**Error Details**

```
I20190725-04:36:00.059(-7)? TypeError: Path must be a string. Received undefined
I20190725-04:36:00.060(-7)?     at assertPath (path.js:28:11)
I20190725-04:36:00.060(-7)?     at Object.join (path.js:1233:7)
I20190725-04:36:00.060(-7)?     at Promise.asyncApply (imports/api/instances/instances.methods.js:247:51)
I20190725-04:36:00.060(-7)?     at /home/myuser/.meteor/packages/promise/.0.11.2.1rxqxdq.d4m4g++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
```
**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser  chrome
 - Version Version 75.0.3770.142

**Comment by engahmed1190** [comment]
After Updating Botfront

I have this error 


```
I20190725-11:26:27.879(-7)?      data:
I20190725-11:26:27.879(-7)?       { version: '1.1.5-b3',
I20190725-11:26:27.879(-7)?         status: 'failure',
I20190725-11:26:27.879(-7)?         message: 'Agent with name \'/home/myuser/odd_lime/models/model-bf.tar.gz\' could not be loaded.',
I20190725-11:26:27.879(-7)?         reason: 'BadRequest',
I20190725-11:26:27.879(-7)?         details: [Object],
I20190725-11:26:27.879(-7)?         help: null,
I20190725-11:26:27.879(-7)?         code: 400 } },
I20190725-11:26:27.880(-7)?   toJSON: [Function] }
```

**Comment by znat** [comment]
Hi @engahmed1190 
We fixed an issue related to model versions. If you don't have valuable data in your model you can just startover.
- Otherwise, update to the latest version
- uncompress the model file, and set version to `1.0.0rc` in `fingerprint.json` then recompress.

**Comment by engahmed1190** [comment]
@znat where I can find `fingerprint.json`

**Comment by engahmed1190** [comment]
Hi @znat .

I have tried your solution but the problem still exists, meteor part can change the model but can't load it.

I have found a workaround to set `MODELS_LOCAL_PATH ` to `/app/models`. it works with me . 

Let me know if we can have a better solution, Thanks for your reply

**Comment by znat** [comment]
Hi closing for now. Feel free to comment if the issue persists
