### ISSUE TITLE
Responses not working for me

### ISSUE THREAD

**Issue by melnichukme** [botfront/botfront#157]
**Describe the bug**
Response does not respond to my rules.

**To Reproduce**
1. Select stories in the sidebar, create a new group called Greetings, paste the content of 2 stories above (starting with chitchat.greet and chitchat.bye) in two dictinct stories, and train.
2. Select NLU from the side bar and go the Chitchat tab. Select chitchat.greet and chitchat.bye, import and train
3. Select Bot responses in the sidebar, then create 2 bot responses. The names of the bot responses are those used in stories:
utter_hi
utter_bye
4. Open chat and write 'Hi' or 'Bye' return chitchat.greet or chitchat.bye... 

**Expected behavior**
I expect him to return the rules I created

**Screenshots**
http://joxi.ru/12MNbDsl0j7YAJ
http://joxi.ru/RmzVnqsYRydemO
http://joxi.ru/MAj9g1Fjx5892e
Json response from Log after sending the message "Hi":
`{'sender_id': '8ad2135fb7cd40ef9816ce4d8513ab58', 'slots': {'followup_response_name': None, 'latest_response_name': None, 'parse_data': None}, 'latest_message': {'intent': {'name': 'chitchat.greet', 'confidence': 0.9568777084350586}, 'entities': [], 'language': 'en', 'intent_ranking': [{'name': 'chitchat.greet', 'confidence': 0.9568777084350586}, {'name': 'chitchat.what_do_you_mean', 'confidence': 0.20752167701721191}, {'name': 'chitchat.you_are_worthless', 'confidence': 0.1871110498905182}, {'name': 'chitchat.you_are_welcome', 'confidence': 0.1731826514005661}, {'name': 'chitchat.you_are_annoying', 'confidence': 0.16573593020439148}, {'name': 'basics.request_handover', 'confidence': 0.12860450148582458}, {'name': 'chitchat.no_problem', 'confidence': 0.12329947203397751}, {'name': 'chitchat.are_you_a_robot', 'confidence': 0.12115823477506638}, {'name': 'chitchat.good_job', 'confidence': 0.11767125129699707}, {'name': 'chitchat.you_are_right', 'confidence': 0.11510945111513138}], 'text': 'Hi'}, 'latest_event_time': 1564971940.4782531, 'followup_action': None, 'paused': False, 'events': [{'event': 'action', 'timestamp': 1564971940.4521692, 'name': 'utter_hi', 'policy': 'policy_2_MemoizationPolicy', 'confidence': 1.0}, {'event': 'bot', 'timestamp': 1564971940.452178, 'text': 'utter_hi', 'data': {'elements': None, 'quick_replies': None, 'buttons': None, 'attachment': None, 'image': None, 'custom': None}, 'metadata': {}}, {'event': 'action', 'timestamp': 1564971940.4782531, 'name': 'action_listen', 'policy': 'policy_2_MemoizationPolicy', 'confidence': 1.0}], 'latest_input_channel': 'webchat', 'active_form': {}, 'latest_action_name': 'action_listen'}`

**Desktop (please complete the following information):**
 - OS: Ubuntu server v 18 (python 3.6)
 - Browser: Google Chrome
 - Version: 75

**Additional context**
Botfront last version.

**Comment by znat** [comment]
Hi @melnichukme , the logs seem correct as `utter_hi` is predicted. What does the bit actually answer?

**Comment by melnichukme** [comment]
@znat I expect utter_hi to be replaced with my rules defined in responses. I expect the text "simple text message".

**Comment by znat** [comment]
And what do you have instead?

**Comment by melnichukme** [comment]
@znat I expect utter_hi to be replaced with my message
http://joxi.ru/DmB0wNhJze5EAP

**Comment by znat** [comment]
Oh I see. Are you running Botfront with the Botfront CLI? Can you verify that the API is running (http://localhost:8080)?

**Comment by melnichukme** [comment]
@znat Maybe I'm doing something wrong. botfront is installed on the virtual machine through docker. Yes, I use botfront cli.
1. Launch - sudo botfront up
2. By the ip address of the virtual machine, I have access to port 8080. http://joxi.ru/Dr8OD6hozelgA6

p.s. Here are the settings
http://joxi.ru/ZrJ0bXhwMEZB2j
http://joxi.ru/LmG0bEhwJVd62l
http://joxi.ru/YmE0bnhwJp6pr6
http://joxi.ru/J2bak1t0GQEjm6
http://joxi.ru/V2VgWBHdK6L0Av

.env
http://joxi.ru/D2P0lDhqk34q23
.botfront.ym
http://joxi.ru/krD0bOhKJNO4rp

**Comment by znat** [comment]
Can you check in the logs? There must be an error while fetching the response from the API. `botfront logs`

**Comment by melnichukme** [comment]
@znat
After starting docker, I see such a log.
https://pastebin.com/bcJL572L
After sending a message to the hi chat
https://pastebin.com/fv24eKkx

The only error I noticed in the log:
botfront-rasa | 2019-08-05 23:06:07 DEBUG rasa.core.nlg.callback - Requesting NLG for utter_hi from http: // botfront-api: 8080 / project / bf / nlg.
botfront-rasa | 2019-08-05 23:06:07 ERROR rasa.core.nlg.callback - NLG web endpoint returned an invalid response: 404, Not Found, body = 'b' {"code": 404, "error": "not_found "} ''

**Comment by melnichukme** [comment]
@znat 
I still haven't solved my problem .. I installed ubuntu 19, with python 3.7 but response still doesn't work

Is there any information on my problem? I found another bug. How to reproduce:
1. Open chat
2. Select French
3. Write any word

Result:
There is no response from the server

Logs:

> botfront-rasa | 2019-08-06 22:43:05 ERROR asyncio - Task exception was never retrieved
> botfront-rasa | future: <Task finished coro = <AsyncServer._handle_event_internal () done, defined at /usr/local/lib/python3.6/site-packages/socketio/asyncio_server.py:426> exception = AttributeError ("'NoneType' object has no attribute 'parse' ",) created at /usr/local/lib/python3.6/site-packages/engineio/asyncio_server.py:309>
> botfront-rasa | source_traceback: Object created at (most recent call last):
> botfront-rasa | File "/ usr / local / bin / rasa", line 10, in <module>
> botfront-rasa | sys.exit (main ())
> botfront-rasa | File "/usr/local/lib/python3.6/site-packages/rasa/__main__.py", line 76, in main
> botfront-rasa | cmdline_arguments.func (cmdline_arguments)
> botfront-rasa | File "/usr/local/lib/python3.6/site-packages/rasa/cli/run.py", line 92, in run
> botfront-rasa | rasa.run (** vars (args))
> botfront-rasa | File "/usr/local/lib/python3.6/site-packages/rasa/run.py", line 54, in run
> botfront-rasa | ** kwargs
> botfront-rasa | File "/usr/local/lib/python3.6/site-packages/rasa/core/run.py", line 179, in serve_application
> botfront-rasa | app.run (host = "0.0.0.0", port = port)
> botfront-rasa | File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 1096, in run
> botfront-rasa | serve (** server_settings)
> botfront-rasa | File "/usr/local/lib/python3.6/site-packages/sanic/server.py", line 770, in serve
> botfront-rasa | loop.run_forever ()
> botfront-rasa | File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 126, in send
> botfront-rasa | return self.gen.send (value)
> botfront-rasa | File "/usr/local/lib/python3.6/site-packages/spf/framework.py", line 476, in _handle_request
> botfront-rasa | stream_callback)
> botfront-rasa | File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
> botfront-rasa | return self.gen.send (None)
> botfront-rasa | File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 917, in handle_request
> botfront-rasa | response = await response
> botfront-rasa | File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
> botfront-rasa | return self.gen.send (None)
> botfront-rasa | File "/usr/local/lib/python3.6/site-packages/engineio/asyncio_server.py", line 238, in handle_request
> botfront-rasa | packets = await socket.handle_get_request (environ)
> botfront-rasa | File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
> botfront-rasa | return self.gen.send (None)
> botfront-rasa | File "/usr/local/lib/python3.6/site-packages/engineio/asyncio_socket.py", line 89, in handle_get_request
> botfront-rasa | return await getattr (self, '_upgrade_' + transport) (environ)
> botfront-rasa | File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
> botfront-rasa | return self.gen.send (None)
> botfront-rasa | File "/usr/local/lib/python3.6/site-packages/engineio/asyncio_socket.py", line 128, in _upgrade_websocket
> botfront-rasa | return await ws (environ)
> botfront-rasa | File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
> botfront-rasa | return self.gen.send (None)
> botfront-rasa | File "/usr/local/lib/python3.6/site-packages/engineio/async_drivers/sanic.py", line 122, in __call__
> botfront-rasa | await self.handler (self)
> botfront-rasa | File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
> botfront-rasa | return self.gen.send (None)
> botfront-rasa | File "/usr/local/lib/python3.6/site-packages/engineio/asyncio_socket.py", line 222, in _websocket_handler
> botfront-rasa | await self.receive (pkt)
> botfront-rasa | File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
> botfront-rasa | return self.gen.send (None)
> botfront-rasa | File "/usr/local/lib/python3.6/site-packages/engineio/asyncio_socket.py", line 42, in receive
> botfront-rasa | run_async = self.server.async_handlers)
> botfront-rasa | File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
> botfront-rasa | return self.gen.send (None)
> botfront-rasa | File "/usr/local/lib/python3.6/site-packages/engineio/asyncio_server.py", line 407, in _trigger_event
> botfront-rasa | ret = await self.handlers [event] (* args)
> botfront-rasa | File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
> botfront-rasa | return self.gen.send (None)
> botfront-rasa | File "/usr/local/lib/python3.6/site-packages/socketio/asyncio_server.py", line 494, in _handle_eio_message
> botfront-rasa | await self._handle_event (sid, pkt.namespace, pkt.id, pkt.data)
> botfront-rasa | File "/ usr / local / lib / p

**Comment by znat** [comment]
Can you try this url in your browser and paste the output here? 
```
http://localhost:8080/project/bf/responses
```

**Comment by znat** [comment]
@melnichukme 
Thank you for submitting bugs!
Would it be ok to post the other bug as a separate issue?

**Comment by znat** [comment]
Thanks @melnichukme 
If you can just paste the ouput of `curl http://localhost:8080/project/bf/responses` that would help understanding your issue

**Comment by melnichukme** [comment]
@znat 
I have 2 projects, one in Russian, the second chitchat in English and French. I checked your request and it returned the following answer:
`{"responses":[{"values":[{"sequence":[{"text":"simple text message"}],"lang":"ru"}],"key":"utter_hi"}],"timestamp":1564963627849}`

Very strange, but in json I only see Russian. I thought that he was somewhere defined as the default language and tried to make a response for him, but the chat still does not respond to me with messages

**Comment by melnichukme** [comment]
@znat 
Hooray, I think I understand what the problem is!
When installing botfront, you are prompted to create your own project. And this project, it seems to me, is the default project and all the data will be related to it, even if you switch to another project:
http://localhost:8080/project/bf/responses always returns your project data. If you switch to chitchat and create response messages for it, they will not work, and even the search for intents will be carried out from your project and not from chitchat ...
http://joxi.ru/L21dN0sRg5p3mX

I understand that the Russian language does not work in botfront? Tell me how can I make it work?

**Comment by znat** [comment]
There is no language limitation in Botfront. However we're currently fixing bugs related to the model not being trained correctly the first time. Fix very soon, but in the meantime you can try these workarounds:
- make sure you have at least 2 intents per language
- add/remove an NLU example
- restart rasa explicitly `botfront restart rasa`

**Comment by melnichukme** [comment]
@znat 
How do I add Russian? If you add the Russian language through the settings, rasa cannot recognize it and highlight intent ... Also, the chit chat tab in the NLU section tells me that the language is not supported.

How do I remove the NLU example? where does it lie on the file drive?

The product is interesting. But I found other errors and would like to tell you more about them, not through github

**Comment by znat** [comment]
There is no chitchat data in Russian, that does not mean that Russian is not supported, just that you'll have to build your own chitchat data (and ideally contribute it :) )
You're saying that you can't train Russian? Have you seen something about it in the Rasa forums?

**Comment by melnichukme** [comment]
@znat
On the forums I read that there are ready-made language files. But where to put them, I do not know. Where is rasa located after installation?

Is it possible to create more than 1 project in botfront? I did not find such an opportunity. For example, I need to make 5 bots, but within one server I can only create one ..

**Comment by znat** [comment]
No, it's one project at a time. Yo can create several projects by running `botfront init` in several folders. We're working on a simpler way to deploy projects so you don't have to deploy the whole stack for each project

**Comment by znat** [comment]
Re Russian, you should not need language files as Botfront comes with the tensorflow pipeline which is supposed to be language agnostic

**Comment by melnichukme** [comment]
@znat 
Added 3 entries to training data, defined intent. Clicked training. In the text box "Users says ..." entered one of 3 phrases and do not get the definition of intent ....
botfront-rasa | 2019-08-08 22:52:45 ERROR rasa.nlu.classifiers.embedding_intent_classifier - There is no trained tf.session: component is either not trained or didn't receive enough training data

I am sorry to realize this, but the product is very raw and almost not working ... very sorry. I was glad to help you

**Comment by znat** [comment]
Hi @melnichukme , the latest release fixes a bunch of issues relating to training.
I tried with Russian (using Google translate) and I could train 2 intents and get the model to interpret utterances correctly. It is true that the app doesn't let you know you need at least two intents with 2 examples each.
Thanks for reporting issues, it's extremely helpful!

**Comment by melnichukme** [comment]
@znat Installed a new version ... and it does not work
http://joxi.ru/n2YVlksbe0ZJA6
After installation, I get to a white screen .. (section "stories"). Changed the configuration from localhost to my real ip adress - nothing has changed.

Also the error is not fixed:
http://joxi.ru/DmB0wNhJ46zGAP

Chat does not open .. in the developer's console errors:

> Error: Cannot find module './docker-compose/Settings.docker-compose'
>     at y (1231d1e8b92370f5b6e0173f6da2b88156e4b9c6.js? meteor_js_resource = true: 7)
>     at d.resolve (1231d1e8b92370f5b6e0173f6da2b88156e4b9c6.js? meteor_js_resource = true: 7)
>     at 1231d1e8b92370f5b6e0173f6da2b88156e4b9c6.js? meteor_js_resource = true: 7
>     at new Promise (<anonymous>)
>     at d.prefetch (1231d1e8b92370f5b6e0173f6da2b88156e4b9c6.js? meteor_js_resource = true: 7)
>     at d.o.dynamicImport (1231d1e8b92370f5b6e0173f6da2b88156e4b9c6.js? meteor_js_resource = true: 25)
>     at g.componentDidMount (1231d1e8b92370f5b6e0173f6da2b88156e4b9c6.js? meteor_js_resource = true: 149)

And also (there is no localhost in the settings):

> Failed to load resource: net :: ERR_CONNECTION_REFUSED
> http: // localhost: 8888 / __ meteor __ / dynamic-import / fetch

For two weeks, I could not use your product))

**Comment by znat** [comment]
Regarding your first screenshot:
1) Why do you need `sudo`
2) It seems that two versions are mixed up. The latest version doesn't need a default model but the cli still tries find it. And it's not something I can reproduce. Can you try to completely uninstall and reinstall botfront?
```
npm uninstall -g botfront
npm install -g botfront
```

**Comment by znat** [comment]
Evaluation is indeed broken. Just created an issue, Thanks for reporting

**Comment by melnichukme** [comment]
> Regarding your first screenshot:
> 
> 1. Why do you need `sudo`
> 2. It seems that two versions are mixed up. The latest version doesn't need a default model but the cli still tries find it. And it's not something I can reproduce. Can you try to completely uninstall and reinstall botfront?
> 
> ```
> npm uninstall -g botfront
> npm install -g botfront
> ```
> 
> Also, are you changing stuff? Can you paste the content of you `botfront.yml`(in `.botfront`)

1. because without sudo, the server starts up with errors ..
2. I uninstalled the global package and reinstalled. It did not help. When I go to http: // ip-adress: 8888 / project / bf / stories
I get errors in the developer console:
http://joxi.ru/Dr8OD6hoMpwKA6

Apparently, this is somehow connected with "CORS", but this was not before .. I installed the extension for chrome which replaces the headers, but still get errors and a white screen
http://joxi.ru/KAgXN8fEKVQ7rl

**Comment by znat** [comment]
Should be fixed. Feel free to re-open if the issue persists
