### ISSUE TITLE
Switching the language in the chat window

### ISSUE THREAD

**Issue by melnichukme** [botfront/botfront#164]
**Describe the bug**
When you switch the language from English to French, the chat refuses to respond to messages. There are errors on the server after the language is switched

**To Reproduce**
1. Open chat
2. Select French
3. Write any word
4. Check server log (botfront logs)

**Expected behavior**
After switching the language, the chat should respond to messages. There should be no errors on the server

**Desktop (please complete the following information):**
- OS: Ubuntu server v 19 (python 3.7)
- Browser: Google Chrome
- Version: 75

**Additional context**
An error was detected in the pre-installed chitchat model. Server Logs:

> botfront-rasa | 2019-08-06 22:43:05 ERROR asyncio - Task exception was never retrieved
> botfront-rasa | future: <Task finished coro = <AsyncServer._handle_event_internal () done, defined at /usr/local/lib/python3.6/site-packages/socketio/asyncio_server.py:426> exception = AttributeError ("'NoneType' object has no attribute 'parse' ",) created at /usr/local/lib/python3.6/site-packages/engineio/asyncio_server.py:309>
> botfront-rasa | source_traceback: Object created at (most recent call last):
> botfront-rasa | File "/ usr / local / bin / rasa", line 10, in 
> botfront-rasa | sys.exit (main ())
> botfront-rasa | File "/usr/local/lib/python3.6/site-packages/rasa/main.py", line 76, in main
> botfront-rasa | cmdline_arguments.func (cmdline_arguments)
> botfront-rasa | File "/usr/local/lib/python3.6/site-packages/rasa/cli/run.py", line 92, in run
> botfront-rasa | rasa.run (** vars (args))
> botfront-rasa | File "/usr/local/lib/python3.6/site-packages/rasa/run.py", line 54, in run
> botfront-rasa | ** kwargs
> botfront-rasa | File "/usr/local/lib/python3.6/site-packages/rasa/core/run.py", line 179, in serve_application
> botfront-rasa | app.run (host = "0.0.0.0", port = port)
> botfront-rasa | File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 1096, in run
> botfront-rasa | serve (** server_settings)
> botfront-rasa | File "/usr/local/lib/python3.6/site-packages/sanic/server.py", line 770, in serve
> botfront-rasa | loop.run_forever ()
> botfront-rasa | File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 126, in send
> botfront-rasa | return self.gen.send (value)
> botfront-rasa | File "/usr/local/lib/python3.6/site-packages/spf/framework.py", line 476, in _handle_request
> botfront-rasa | stream_callback)
> botfront-rasa | File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in next
> botfront-rasa | return self.gen.send (None)
> botfront-rasa | File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 917, in handle_request
> botfront-rasa | response = await response
> botfront-rasa | File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in next
> botfront-rasa | return self.gen.send (None)
> botfront-rasa | File "/usr/local/lib/python3.6/site-packages/engineio/asyncio_server.py", line 238, in handle_request
> botfront-rasa | packets = await socket.handle_get_request (environ)
> botfront-rasa | File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in next
> botfront-rasa | return self.gen.send (None)
> botfront-rasa | File "/usr/local/lib/python3.6/site-packages/engineio/asyncio_socket.py", line 89, in handle_get_request
> botfront-rasa | return await getattr (self, 'upgrade' + transport) (environ)
> botfront-rasa | File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in next
> botfront-rasa | return self.gen.send (None)
> botfront-rasa | File "/usr/local/lib/python3.6/site-packages/engineio/asyncio_socket.py", line 128, in _upgrade_websocket
> botfront-rasa | return await ws (environ)
> botfront-rasa | File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in next
> botfront-rasa | return self.gen.send (None)
> botfront-rasa | File "/usr/local/lib/python3.6/site-packages/engineio/async_drivers/sanic.py", line 122, in call
> botfront-rasa | await self.handler (self)
> botfront-rasa | File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in next
> botfront-rasa | return self.gen.send (None)
> botfront-rasa | File "/usr/local/lib/python3.6/site-packages/engineio/asyncio_socket.py", line 222, in _websocket_handler
> botfront-rasa | await self.receive (pkt)
> botfront-rasa | File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in next
> botfront-rasa | return self.gen.send (None)
> botfront-rasa | File "/usr/local/lib/python3.6/site-packages/engineio/asyncio_socket.py", line 42, in receive
> botfront-rasa | run_async = self.server.async_handlers)
> botfront-rasa | File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in next
> botfront-rasa | return self.gen.send (None)
> botfront-rasa | File "/usr/local/lib/python3.6/site-packages/engineio/asyncio_server.py", line 407, in _trigger_event
> botfront-rasa | ret = await self.handlers [event] (* args)
> botfront-rasa | File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in next
> botfront-rasa | return self.gen.send (None)
> botfront-rasa | File "/usr/local/lib/python3.6/site-packages/socketio/asyncio_server.py", line 494, in _handle_eio_message
> botfront-rasa | await self._handle_event (sid, pkt.namespace, pkt.id, pkt.data)
> botfront-rasa | File "/ usr / local / lib / p

**Comment by znat** [comment]
Closing as I think this works fine now. Feel free to re-open if the issue persists
