### ISSUE TITLE
dispatcher.utter_message not working

### ISSUE THREAD

**Issue by engahmed1190** [botfront/botfront#172]
**Describe the bug**
dispatcher.utter_message doesn't print out the message 

**To Reproduce**
1. Open the actions folder and add a new file called my_actions.py 

```
import logging
from functools import reduce
from rasa_core_sdk import Action
from rasa_core_sdk.events import SlotSet, ReminderScheduled

logging.basicConfig(level="DEBUG")
logger = logging.getLogger()

class GuestsAction(Action):

    def name(self):
        return 'action_guests'

    def run(self, dispatcher, tracker, domain):
    
            dispatcher.utter_message("How many are you?")
            return []

```

**Comment by znat** [comment]
@engahmed1190 thanks for reporting this

**Comment by pheel** [comment]
@engahmed1190 Please reopen this if need be.

Back in pre-v0.16.0 days the file structure of the actions directory was messed up.
