### ISSUE TITLE
Evaluation broken - returns an error

### ISSUE THREAD

**Issue by znat** [botfront/botfront#174]
**To Reproduce**
1. Import data
2. train
3. evaluate

From #157 
**Screenshots**
<img width="646" alt="Capture d’écran 2019-08-15 à 20 17 59" src="https://user-images.githubusercontent.com/3694634/63134989-e7b7e180-bf99-11e9-80e9-640a4cdcd903.png">

**Comment by beevelop** [comment]
Yep, we are currently experiencing the same issue.
