### ISSUE TITLE
Accentuated characters at the end of words can't be selected for entity annotation

### ISSUE THREAD

**Issue by midemarc** [botfront/botfront#177]
**Describe the bug**

It is not possible to fully select a word that ends in an accentuated character to add an entity to it.

**To Reproduce**
1. Create a NLU example with a word that ends with an accentuated character, e.g. "compte chèque verrouillé".
2. Select the word "verrouillé" and click on it to add an entity
3. The "é" character gets dropped from the selection

**Expected behavior**
1. The selection by "dragging" the mouse over characters should be kept when clicking on the word to add an entity.
2. Double-clicking on a word that ends in an accentuated character should select all of it.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 76.0.3809.100

**Comment by znat** [comment]
Thanks for reporting this.

**Comment by znat** [comment]
@MatthieuJnon  any updates?

**Comment by znat** [comment]
@MatthieuJnon

**Comment by MatthieuJnon** [comment]
Hi @midemarc, this is fixed in the latest version 0.16.0-rc.12, please update to that one
