### ISSUE TITLE
Rasa core does not work fine for me

### ISSUE THREAD

**Issue by Asma-droid** [botfront/botfront#205]
Hi all,

As i have remarked, entities have not been taken into consideration in the domain file. Accordingly, there have been ignored in the featurization step. This may affect the prediction of the next action? Have you any idea?

Thank you in advance

**Comment by znat** [comment]
Hi @Asma-droid , thanks for reporting this. We'll look into it shortly

**Comment by pheel** [comment]
@Asma-droid, can you elaborate on the use case you have that's affected?

As things are, an entity "entity_name" get added to the core domain if and only if you have a story that mentions it, i.e. a line like "* my_intent{"entity_name": "entity_value"}".

**Comment by Asma-droid** [comment]
For a given dataset and a given configuration, i have tested two rasa versions rasa 1.2.7 in CLI and botfront. The two rasa versions predict differently the next action. When comaparing the input for each version, i have seen that the domain and the featurization are not the same.

**Comment by znat** [comment]
@Asma-droid when you extract your model zip file and inspect your domain, do you see missing entities?

**Comment by Asma-droid** [comment]
@znat yes in my domain file i have entities:[] but in my sotries i have no line like "* my_intent{"entity_name": "entity_value"}".

**Comment by pheel** [comment]
Having vs not having those entities in domain creates two different models indeed, but I wonder if a case can be made that your original model performs better given your usage? (One where no action prediction depends on the presence or absence of an entity)

**Comment by Asma-droid** [comment]
My problem is that i have a botfront model and i have a a rasa model with the version 1.2.7. For the two models i have almost the same file featurizer.json but models differ in predictions.

**Comment by znat** [comment]
Hi @Asma-droid is the issue still present in the latest version or can we close?
