### ISSUE TITLE
Error: Slot was not found. Have you defined it?

### ISSUE THREAD

**Issue by vitalyuf** [botfront/botfront#221]
I'm passing QucikStart guide.
Currently I'm trying to branch stories using slots.

1. At stories->Slots tab I added a slot:
name=bookclass
initial value=not_set
Categories: eco/business/not_set
and saved it

2. At stories->stories tab I defined a story (in additino to the rest at "CancelBooking" story group):
* cancel_booking
- slot{"bookclass":"eco"}
- utter_booking_not_cancellable

But botfront shows me an error "Slot was not found. Have you defined it?" at "- slot{"bookclass":"eco"}" string.

But "Train everything" doesn't throw errors.

Maybe I'm doing something wrong?

**Comment by MatthieuJnon** [comment]
This is indeed a bug, it's being fixed now, and will be resolved in the next release. You can expect the release by the end of the week.

**Comment by vitalyuf** [comment]
Ok, thanks
Should I close the issue now?

**Comment by znat** [comment]
@MatthieuJnon fixed?

**Comment by MatthieuJnon** [comment]
This is fixed, merged and released, closing the issue.
