### ISSUE TITLE
Entities are randomly selected

### ISSUE THREAD

**Issue by znat** [botfront/botfront#23]
**Describe the bug**
Entities are randomly selected

**To Reproduce**
https://mr-bot.slack.com/files/UBGCEGVV1/FJDH92K89/screen_recording_2019-05-10_at_12.15.03.mov
https://mr-bot.slack.com/files/UBGCEGVV1/FJKBQ27JQ/screen_recording_2019-05-10_at_12.00.03.mov

**Comment by MatthieuJnon** [comment]
Fixed in #24
