### ISSUE TITLE
Multiple utterance variants

### ISSUE THREAD

**Issue by nickhamilton1980** [botfront/botfront#232]
Hi Guys, 

Maybe I am not doing something right, but in Rasa, if in the domain file, a single utterance is defined and repeated like as follows:

**domain.yml**
```
  utter_something:
  - text: Something ABC
  - text: Something Else
  - text: And again
  - text: Yes, again
```

Then usage of `utter_something` in a story somewhere, will yield only **ONE** of the possibilities picked at **RANDOM**.

However, the equivalent in `Botfront` seems to be responding with **ALL** of them, which is nonsensical and would prevent/inhibit a rich tapestry of conversation permutations. 

Various screenshots attached.

I tried putting seperate response definitions in for each possible (intended random selection) response, but only one of each 'Response name' is permitted by the UI.

<img width="1080" alt="Screen Shot 2019-09-30 at 11 13 46 am" src="https://user-images.githubusercontent.com/49050968/65843192-b04b9b80-e373-11e9-88e7-b78716c8bfa6.png">
<img width="323" alt="Screen Shot 2019-09-30 at 11 13 31 am" src="https://user-images.githubusercontent.com/49050968/65843193-b0e43200-e373-11e9-9faa-661f8bc5f159.png">
<img width="1065" alt="Screen Shot 2019-09-30 at 11 13 09 am" src="https://user-images.githubusercontent.com/49050968/65843195-b17cc880-e373-11e9-8929-7f80593e9d35.png">
<img width="514" alt="Screen Shot 2019-09-30 at 11 13 01 am" src="https://user-images.githubusercontent.com/49050968/65843196-b17cc880-e373-11e9-9905-3a1386b022c4.png">

**Comment by pheel** [comment]
Hi Nick,

Response _sequences_ have actually been a core Botfront feature since the early days. Unfortunately, it uses the same notation as Rasa's response _alternatives_. We are currently thinking of ways of increasing cross-compatibility with Rasa, and response alternatives are definitely part of this.

So short answer, response alternatives are not supported by Botfront, but may be in a near future.

**Comment by nickhamilton1980** [comment]
Ok. Well I actually like the 'sequence' feature, because there are a zillion cases where this is going to be so advantageous, thanks for clarifying.

What you need is to be able to accept syntax, something like the following screenshot, which would result in an **alternative at each stage in the sequence**:

<img width="509" alt="Screen Shot 2019-10-03 at 6 59 16 am" src="https://user-images.githubusercontent.com/49050968/66081500-71078f80-e5ab-11e9-833e-40381b26d72a.png">
