### ISSUE TITLE
Is there any other way around without docker image using the botfront?

### ISSUE THREAD

**Issue by azizullah2017** [botfront/botfront#234]
Just to do some customization for myself in UI and I wanted to debug issues which I facing.
I want to create multiple projects. some times UI is showing. train is undefined.

I am using ubuntu. I am unable to find the container or source file of botfront.
Kindly let me know how can edit the source code. I want to use with docker images.

**Comment by pheel** [comment]
Hi @azizullah2017, you are free to download the source code. Refer to the [dev docs](https://docs.botfront.io/developers-guide/) for some guidance on development.
