### ISSUE TITLE
Evaluation throws exception (cannot destructure property 'report')

### ISSUE THREAD

**Issue by beevelop** [botfront/botfront#244]
In the currently available `botfront@0.16.0-rc.10` the Evaluation feature seems to broken. When trying to run any kind of evaluation (either file upload or through the activity tab), the following exception is thrown in the Botfront frontend:
```
TypeError: Cannot destructure property 'report' of '{}' as it is null.
    at x.getPrimaryPanes (a598bcc16375ac00b89878e27278ded85aaaed27.js?meteor_js_resource=true:149)
    at x.render (a598bcc16375ac00b89878e27278ded85aaaed27.js?meteor_js_resource=true:149)
 ```

The referenced function is part of the `Evaluation.jsx`: https://github.com/botfront/botfront/blob/9974bd7f4c1f62d6e2fa1fb43e265466e156e98a/botfront/imports/ui/components/nlu/evaluation/Evaluation.jsx#L56

The Websocket response for the evaluation contains the following payload:
```json
0: "{"msg":"added","collection":"nlu_evaluations","id":"NJobFc8Mi3WwH8FeX","fields":{"results":{"intent_evaluation":null,"entity_evaluation":{},"response_selection_evaluation":null},"modelId":"aGvW4AwHBTcLnK2Es","timestamp":{"$date":1570520856939}}}"
```

**To Reproduce**
1. Spin up a Botfront project
2. Add some training data and train it
3. Create some activity content
4. Choose several validated examples to run for evaluation
5. See a "whitescreen" error

**Expected behavior**
The evaluation should return the expected report.

**Additional context**
```
botfront/rasa-for-botfront:v1.3.3-bf.6
botfront/botfront:v0.16.0-rc.10
botfront/botfront-api:v0.16.1
```

**Comment by pheel** [comment]
Hi @beevelop, thanks for the report. I'm trying to reproduce this on my end. Will get back to you.

**Comment by pheel** [comment]
@beevelop, what happens if you navigate to the Evaluation tab directly? i.e. NLU > Evaluation.

**Comment by beevelop** [comment]
Well, in my case, the view was completely broken and threw the exception all the time, until I restarted the services. Not quite sure, why though.

**Comment by pheel** [comment]
Previous code did not leave slack for null test results.

**Comment by beevelop** [comment]
Awesome, thank you @pheel. 🍻
