### ISSUE TITLE
doc: host.docker.internal not supported on Linux

### ISSUE THREAD

**Issue by znat** [botfront/botfront#25]
Probably should add a warning in the doc refering to the docker issue https://github.com/docker/for-linux/issues/264

**Comment by MatthieuJnon** [comment]
Resolved in #26

**Comment by pheel** [comment]
Linux support for this hostname has been implemented and is likely coming in the next days/weeks: https://github.com/docker/libnetwork/pull/2348

I found that best practice however might be to refer (in the environment var file and the db) to containers by their container name on the Docker network defined by docker-compose.yml.

host.docker.internal:5000 -> nlu:5000
host.docker.internal:**8081** -> botfront-api:**8080** (container port and not exposed port)
etc.

**Comment by MatthieuJnon** [comment]
Support might be coming in a few days but it will probably take years for all linux distros to ship with the right docker version.

We arrived at the same conclusion for using containers names, it's in the work and requires testing.

**Comment by MatthieuJnon** [comment]
It is now working on Linux, you can run `docker rmi botfront/botfront -f` to remove the image and then run `docker-compose up` again in [botfront-starter](https://github.com/botfront/botfront-starter), so that it downloads the latest version of the image
