### ISSUE TITLE
Facebook Deployment Issues

### ISSUE THREAD

**Issue by aintHuman** [botfront/botfront#253]
Issue trying to deploy on Facebook. 

Initially I run on my local machine using ngrok secure tunnel to my machine. Note, I am using methods which have worked for me in the past with rasa deployments.

In my prior rasa deployments, the following was added to `credentials.yml`

```
#facebook:
facebook:
  verify: "<verify>"
  secret: "<secret>"
  page-access-token: "<token>"
```

And in FaceBook, the following was used as the callback:

`<URL>/webhooks/facebook/webhook/`

where `<URL>` is the deployment URL, so, in the case where ngrok was being used, it might be something like this:

`https://XXXXXXXX.ngrok.io -> http://localhost:5005`

Now if I do all the above with BotFront (including specifying the credentials in the particular language NLU settings), the messages are detected by the ngrok listener, and provide status code 200 for the http request, but no payload is actually delivered.

So, given that Botfront has been dockerised using various docker containers, are the callback addresses correct (ie `<URL>/webhooks/facebook/webhook/`), and, is the 5005 the right port to listen on?

**Comment by znat** [comment]
Hey @nickhamilton1980 , we still need to make an adaptation to the messenger channel so it works with our multilingual feature... The only supported channel is the webchat at the moment. That being said, we need to do it anyways so may be it's a good time...

**Comment by nickhamilton1980** [comment]
Is this mentioned anywhere in your documentation? Its kinda important to know, given the prevalence of FB messenger bots, and other channels for that matter ...

**Comment by znat** [comment]
Here: https://docs.botfront.io/deployment/frontend/#backend-configure-the-channel
But still, we'll discuss how we can prioritize this

**Comment by nickhamilton1980** [comment]
I see, my apologies.

**Comment by aintHuman** [comment]
Nathan, do you have any idea when this feature might be available?

**Comment by MatthieuJnon** [comment]
Hi @aintHuman, if you're using a new version of Botfront you will be able to use Facebook Messenger with Botfront. See [Deploying your Rasa assistant on several channels](https://botfront.io/docs/channels/#deploying-your-rasa-assistant-on-several-channels)
