### ISSUE TITLE
Chatbot textfield not working in Firefox

### ISSUE THREAD

**Issue by aintHuman** [botfront/botfront#254]
CSS issue, the textfield not positioned correctly in a Firexfox browser, screenshot attached.

Perhaps absolute positioning, 45px from the bottom, with explicit 100% width. This fixes for firefox, haven't tested on other browsers. Chrome works fine out of the box as you probably know.

**Problem Highlight**

<img width="343" alt="Screen Shot 2019-10-11 at 1 10 59 pm_edit" src="https://user-images.githubusercontent.com/49050968/66619778-e0275880-ec29-11e9-993a-e17bd2961dbb.png">

**Proposed Changes:**

<img width="1037" alt="Screen Shot 2019-10-11 at 1 14 54 pm_edit" src="https://user-images.githubusercontent.com/49050968/66619812-fe8d5400-ec29-11e9-8e18-9b1d1f9a5198.png">

**Fixed:** 

<img width="323" alt="Screen Shot 2019-10-11 at 1 18 52 pm" src="https://user-images.githubusercontent.com/49050968/66619819-051bcb80-ec2a-11e9-912f-4dc3dd21b923.png">

**Comment by pheel** [comment]
https://github.com/botfront/botfront/commit/882d2b9582be5c2a69021f85426b2eba5cb0bed3
