### ISSUE TITLE
Couldn't run botfront on Ubuntu 16.04

### ISSUE THREAD

**Issue by udaybmi** [botfront/botfront#255]
I installed botfront using "npm install -g botfront", but I'm trying to start botfront using "botfront" cmd in the terminal and command not found msg is coming

![botfront](https://user-images.githubusercontent.com/45415283/66633268-0f3cca80-ec28-11e9-81ac-3ad5b5fee0be.png)

**Comment by znat** [comment]
I think this might be related to the fact you're installing with sudo. 
For some reason, the link is not done correctly.
I guess you can still use the full path (line 2 in your screenshot)

**Comment by MatthieuJnon** [comment]
Hi, if you have to use npm with sudo, it's probably that something in your installation of node is broken. Even if you use the full path, it probably has right only for root user.

Refer to this documentation on npm website to fix your node installation : 
https://docs.npmjs.com/common-errors#resolving-eacces-permissions-errors-when-installing-packages-globally
