### ISSUE TITLE
Story Recursive Link

### ISSUE THREAD

**Issue by aintHuman** [botfront/botfront#258]
I have a situation where I want a user to be able to navigate through a sort of menu system. Like lets say a list of items, user is able to move forward to the next item,  backward to the previous item, and show info on the present item.

After the information is presented, user would be given the option (by utterance) to move forward / move backward and therefore show the same info on the newly selected item.

Think like the menu systems in some of the older C++ command-line executables.

```
+----+
|    |
|    V
|
|  Start
|    |
|    +--------+-----+--------+
|    |        |     |        |
|   Back     Fwd   Info     Exit
+----+        |     |        |
|             |     |        |
+-------------+     |        |
|                   |        |
+-------------------+        |
			     |
                             +-------> Something Else
```

So in the story definitions, whilst one story can link to another story, **it cannot link to itself** (UI prevents that). The scenario above would work perfectly if I could link one or more branches back to the same story, to start over. 

To prevent circular loop, only one branch needs to not link at all, or at least link to some other story.

I had actually achieved this in stock-standard rasa via form action, but I think forms are not functioning with Botfront.

**Comment by MatthieuJnon** [comment]
That's totally a valid use case. We'll look into it and if it plays well with rasa, we will add it to the app

**Comment by aintHuman** [comment]
Great, wonderful.

**Comment by GuillaumeTech** [comment]
The modification has been merge.
Just a little detail, you need an "intro story" to enter the loop, e.g : the Get started story could link to the story with the self links
```
     |
Get started
     |
     |
+----+
|    |
|    V
|
|  Start
|    |
|    +--------+-----+--------+
|    |        |     |        |
|   Back     Fwd   Info     Exit
+----+        |     |        |
|             |     |        |
+-------------+     |        |
|                   |        |
+-------------------+        |
			     |
                             +-------> Something Else
```

**Comment by aintHuman** [comment]
Thanks very much.

Can someone point me in the right direction please. What is the procedure for re-building and installing from git repository, in preference to NPM?

NPM is at version 0.16.2, whereas, the git repository is more advanced, ~0.16.4 or thereabouts.

https://www.npmjs.com/package/botfront

In other words, with respect to the command `npm install -g botfront`, what achieves the equivalent outcome, yet sourced from git?

**Comment by GuillaumeTech** [comment]
Hi !
The npm version is now at botfront 0.17 ! It includes the changes on story linking.
In the future If you want to build from the  repository, you can refer to the developer's guide
#Install : https://docs.botfront.io/developers-guide

**Comment by aintHuman** [comment]
Great thanks. Excellent.

**Comment by engahmed1190** [comment]
Hi @GuillaumeTech 

Can we add this to the documentation? .  With quick example.
