### ISSUE TITLE
Story Group Incorrect Index

### ISSUE THREAD

**Issue by aintHuman** [botfront/botfront#260]
When renaming a story group, by clicking on the ellipsis on the right hand side, the incorrect index is used when populating the edit box with the correct starting value.

Someone has used index `[1 ... n]`, instead of javascript `[0 ... n-1]` ie, `0` based indexing.

Screenshot attached. Trying to edit the first item ('Blocks') to a different name, the initial starting value provided to the edit box is provided as the name of the next item (ie in this case 'Default Stories'). 

Furthermore, trying to save using the initial default value actually fails with error, since the name must be unique and it clashes with the actual 'Default Stories' group.

If I had a guess, the index 1 was probably used (instead of 0), thinking that the 'intro-stories' was part of the array, instead I suspect it is held in a different variable, perhaps.

I note that the last item is assigned the correct value, so there is obviously a check somewhere that the index is in range, or the index number is clamped using something like `min(index, n-1)`

## Group to edit

![image](https://user-images.githubusercontent.com/49050968/66691520-c007a000-ece2-11e9-9c3c-fc0d979a52e2.png)

### This is the problem:

The text box of the selected group, when editing, is assigned the name of the next item in the list

![image](https://user-images.githubusercontent.com/49050968/66691523-c269fa00-ece2-11e9-9fba-ed8f662cccab.png)

## Error: 

If the edit is commenced, but nothing is actually changed, the name therefore clashes with the next item

<img width="334" alt="Screen Shot 2019-10-12 at 11 32 33 am" src="https://user-images.githubusercontent.com/49050968/66691721-132e2280-ece4-11e9-8ddf-ce2c2dbdb061.png">

## The Last item 

Note, this is is assigned correct value

<img width="312" alt="Screen Shot 2019-10-12 at 11 37 02 am" src="https://user-images.githubusercontent.com/49050968/66691806-b121ed00-ece4-11e9-99b0-2649735922b3.png">

**Comment by znat** [comment]
Hey @aintHuman , thanks for reporting this. We're looking into it.
