### ISSUE TITLE
No space on disk error when installing through GCP

### ISSUE THREAD

**Issue by vishnupriyavr** [botfront/botfront#262]
Hi all,
Irrespective of how much I increase the disk space on GCP,I keep on getting this error.
I suspect this is not due to insufficient disk space.Please help and clarify on this.

Error:
Sep 29 05:22:29 instance-2 docker.dockerd[3392]: time="2019-09-29T05:22:29.064594852Z" level=debug msg="Cleaning up layer fbd4ba0a1cc01c8e372029e20734b1b3957ecd0fc687b3cef2eb4f8894de3a
e2: Error processing tar file(exit status 1): write /root/.stack/indices/Hackage/01-index.tar: no space left on device"

**Comment by znat** [comment]
That is related to the Docker environment.
Try running `docker system prune` or `docker system prune --all`

**Comment by vishnupriyavr** [comment]
Hi @znat ,
Even after running the suggested command `docker system prune --all`  and re-running the command `npm install -g botfront`, I am getting the same error.
Please find below the error message for your reference.  
                                                                       
```
│' stderr = 'failed to register layer: Error processing tar file(exit status 1): write /duckling/.stack-work/dist/x
86_64-linux/Cabal-1.24.2.0/build/duckling-expensive/duckling-expensive: no space left on device│
│'                                                                                                                  
```

**Comment by znat** [comment]
Closing as it's a problem of no remaining space on your computer. If you have further issues, feel free to ask a question here: https://spectrum.chat/botfront
