### ISSUE TITLE
Fix menu

### ISSUE THREAD

**Issue by ideivitcom** [botfront/botfront#270]
I don't like at all the menu behaviour. Appearing and disappearing constantly. 

I suggest fix it:

- With all the content
- With the reduced size (because I know what each option does only with the symbol once I've learned)

This behaviour must be a configurable option from settings.

Best regards.

**Comment by znat** [comment]
Hi, thanks for the feedback. Closing for now as it's not a priority for us, but we welcome PRs if you want to contribute
