### ISSUE TITLE
Blank page when clicking on "stories" or "Try out your chabot"

### ISSUE THREAD

**Issue by mroyce1** [botfront/botfront#280]
**Describe the bug**
Hi everyone,

whenever I open the stories page within botfront, the page loads for a fraction of a second and then a blank page appears (url changes to `/project/bf/stories`). During that time, I can briefly see the page in a not fully loaded state. The same thing happens when I click on "Try out your bot" in the bottom right corner. The problem occurs in both Chrome and Firefox (disabled all plugins and cleared cache/cookies to make sure).

As the stories page is the default landing page after login, I can circumvent this by immediately clicking on "NLU" or another link in the left-hand tab. However, as the other features cannot be used, this is highly impractical.

This also happens when selecting the predefined chitchat bot.

`botfront logs` doesn't show any error messages when this happens.
I also manually checked the docker logs for the `botfront/botfront:v0.16.2` container bot to no avail.

**To Reproduce**
1. Go to ip:8888
2. Create an account and login
3. Stories page (landing page) loads for a fraction of a second with the content not being fully rendered yet (i.e. text is grey lines)
4. Page turns blank

**Expected behavior**
Show the stories page/open a chat widget so I can test the bot.

**Desktop (please complete the following information):**
 - OS running botfront: Ubuntu 18.04
 - Browser Chrome 77.0.3865.120  /   Firefox 69.0.3   both on Windows 10 64bit
 - botfront Version 0.16.2

**Screenshot of the partially loaded page before it turns blank:**
[link](https://i.imgur.com/VIFGXzS.png)

**Comment by znat** [comment]
Thanks for reporting!. @GuillaumeTech , didn't you encounter a similar issue yesterday?

**Comment by MatthieuJnon** [comment]
Hi, can you open the developer tools and paste here the error that appears in the console when the app crashes ?

**Comment by GuillaumeTech** [comment]
Yes, I had the same issue when I clicked on "Try out your bot", It was solved doing a localStorage.clear() in the developper console, but I believe it was a browser specific issue, so might not be the same as you experiencing

**Comment by GuillaumeTech** [comment]
Hi, 
It seems that you are running botfront from another machine that the one trying to access it. By default botfront is setup to be accessed from the localhost, you have to setup environment variables if you want to run it on a server: https://docs.botfront.io/deployment/installation/#environment-variables

if you are running botfront from the npm package, you should only have to modify the ROOT_URL environment variable.

**Comment by Xaviertoor** [comment]
This happens to me when I try to access externally, which file would we have to insert ROOT_URL

**Comment by LLLowen** [comment]
> Hi,
> It seems that you are running botfront from another machine that the one trying to access it. By default botfront is setup to be accessed from the localhost, you have to setup environment variables if you want to run it on a server: https://docs.botfront.io/deployment/installation/#environment-variables
> 
> If you are running botfront from the npm package, you should only have to modify the ROOT_URL environment variable.

how to setup?

**Comment by znat** [comment]
Closing as it does not seem to be a bug. Feel free to comment or to ask a question on the Spectrum community: https://spectrum.chat/botfront
