### ISSUE TITLE
Handle connection error to NLU service

### ISSUE THREAD

**Issue by pheel** [botfront/botfront#29]
Right now, if NLU server returns error response, the top right 'train' button keeps spinning, and the 'minutes ago' counter keeps increasing. Input in 'User says...' box correctly warns about response.

**Comment by eziolotta** [comment]
I have the same error, I think you need to set the correct URL for the NLU service, go to setting -> instances -> NLU, I tried localhost: 5000, but it didn't work

**Comment by eziolotta** [comment]
Calling the NLU service with the same parameters that i see on the terminal (docker) :
Browser url:
http://localhost:5000/parse?model=mf5cwSBgBAkBSc59L&nolog=true&project=my-first-project&q=tanks
Response:
"error": "No project found with name 'my-first-project'.

So this should be the cause of the 404 error that returns the GUI when you type something on "user say...". 
 Botfront  didn't create the Rasa NLU project correctly? I followed the procedure by first creating the account and then a new project, imported the chit-chat (english), the training process  did not return errors but in folder models/nlu i don't see the saved model.

PS: in settings->instances->nlu  endpoint is: http://nlu:5000

**Comment by eziolotta** [comment]
ok, sorry. 
you must first import chit-chat, then train NLU model, at this point you can start to input text on "user say...", sorry, I didn't understand the generic error 404 not found (...the model precisely)
