### ISSUE TITLE
Error on docker-compose up botfront-starter

### ISSUE THREAD

**Issue by gothax** [botfront/botfront#32]
**Describe the bug**
When i do the docker-compose up for the botfront-starter project, It loops with an error and it is never available.

`core_1          | :0: UserWarning: You do not have a working installation of the service_identity module: 'No module named 'service_identity''. 
Please install it from <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are satisfied.  Without the service_identity module, Twisted can perform only rudimentary TLS client hostname verification.  Many valid certificate/hostname mappings may be rejected.

core_1          | 2019-05-14 12:50:10 INFO     root  - Rasa process starting

core_1          | 2019-05-14 12:50:10 INFO     root  - Fetching endpoints from server

core_1          | 2019-05-14 12:50:10 DEBUG    utils  - Requesting endpoints from server 
http://host.docker.internal:8081/project/my-first-project/endpoints...

core_1          | 2019-05-14 12:50:10 WARNING  utils  - Tried to fetch endpoints from server, but server response status code is 401.

core_1          | 2019-05-14 12:50:10 INFO     root  - Fetching credentials from server

core_1          | 2019-05-14 12:50:10 DEBUG    utils  - Requesting credentials from server 
http://host.docker.internal:8081/project/my-first-project/credentials...

core_1          | 2019-05-14 12:50:10 WARNING  utils  - Tried to fetch credentials from server, but server response status code is 401.

core_1          | Traceback (most recent call last):
core_1          |   File "/usr/local/lib/python3.5/runpy.py", line 193, in _run_module_as_main
core_1          |     "__main__", mod_spec)
core_1          |   File "/usr/local/lib/python3.5/runpy.py", line 85, in _run_code
core_1          |     exec(code, run_globals)
core_1          |   File "/app/run_core.py", line 100, in <module>
core_1          |     project_id=_endpoints.nlu.kwargs.get('project'),
core_1          | AttributeError: 'NoneType' object has no attribute 'kwargs'
botfront-starter_core_1 exited with code 1`

There is the log of my error.

**To Reproduce**
`git clone http://github.com/botfront/botfront-starter`

`cd botfront-starter`

`docker-compose up`

**Expected behavior**

**Screenshots**
https://imgur.com/tl7QYJe

Thanks for the help in advance

**Comment by znat** [comment]
Hey @gothax, yes that's because there is not project yet so Core restarts until the Botfront's is setup.
https://docs.botfront.io/guide/getting-started/quick-start.html#install-botfront

**Comment by pheel** [comment]
This is not an issue with the botfront frontend but I suspect rather with the use of host.docker.internal. Are you using the Linux version of Docker?

Rebuilding with a new Dockerfile_core removes the UserWarning given by core but did not get ride of the 401 error in my case.
```
...
RUN pip install -r /app/requirements.txt --no-cache-dir
RUN pip install --no-cache-dir service_identity
COPY ./core .
...
```

A temporary fix was to use workarounds to resolve host.docker.internal and to comment out

```
const project = await getVerifiedProject(projectId, req);
if (!project) throw { code: 401, error: 'unauthorized' }
```
in botfront-api/server/credentials/credentials.controller.js and botfront-api/server/endpoints/endpoints.controller.js.

However, when running the stack with docker-compose, changing every mention of **host.docker.internal:8081** (an alias for the Docker host and the exposed port) to **botfront-api:8080** (the container's name on the Docker network and the internal port) works, without rebuilding any containers.

**Comment by amitbend** [comment]
@pheel can you share the changes you've made to make the docker compose work?
I've changed the `host.docker.internal:8081` to `botfront-api:8080` in local.env file but still couldn't make it work

**Comment by pheel** [comment]
@amitbend if you make the following two changes to local.env:
```
MONGO_URL=mongodb://mongo:27017/bf
BF_URL=http://botfront-api:8080
```
... you should be able to access the app from your browser at http://localhost:8888. From there, in Settings > More Settings > Docker Compose, change the API host URL there too. Ditto for Settings > Endpoints (botfront-api:8080, nlu:5000, actions:5055).

**Comment by gothax** [comment]
Hello

Thanks for your  answers.

My problem is solved, in fact, the rasa_core is not initialized while you don't init your first project on the UI. 

Now it's ok. 

Thanks & have a good day guys !

**Comment by MatthieuJnon** [comment]
@gothax @amitbend @pheel 
It is now working on Linux, you can run `docker rmi botfront/botfront -f` to remove the image and then run `docker-compose up` again in [botfront-starter](https://github.com/botfront/botfront-starter), so that it downloads the latest version of the image

**Comment by rajesh67** [comment]
> Hello
> 
> Thanks for your answers.
> 
> My problem is solved, in fact, the rasa_core is not initialized while you don't init your first project on the UI.
> 
> Now it's ok.
> 
> Thanks & have a good day guys !

Can you please share how you got rid of the 401 error.
