### ISSUE TITLE
Meteor recommends using native bcrypt implementation

### ISSUE THREAD

**Issue by beevelop** [botfront/botfront#321]
When launching the Botfront service with the most recent release `v0.18.1`, the following information is getting printed by Meteor:
```
botfront_1      | Note: you are using a pure-JavaScript implementation of bcrypt.
botfront_1      | While this implementation will work correctly, it is known to be
botfront_1      | approximately three times slower than the native implementation.
botfront_1      | In order to use the native implementation instead, run
botfront_1      |
botfront_1      |   meteor npm install --save bcrypt
botfront_1      |
botfront_1      | in the root directory of your application.
```

I guess, in the most usual deployments, the performance boost might be insignificant. Nonetheless it might save some resources in the long run.

**Comment by znat** [comment]
We had problems building the Docker image with native bcrypt. Since it's only used for the login, we can live with the performance impact for now
