### ISSUE TITLE
Creating botfront-mongo    ... error

### ISSUE THREAD

**Issue by sanjaykhanssk** [botfront/botfront#369]
**Describe the bug**
Botfront up not executing, it shows error 

**Expected behavior**
ERROR: for mongo  Cannot create container for service mongo: Conflict. The container name "/botfront-mongo" is already in use by container "24d46db7b2a311f6d1be7d322df8366571d25b425851a6c387a2753329db40b7". You have to remove (or rename) that container to be able to reuse that name.

**Screenshots**
https://ibb.co/F4QF6fd

**Desktop :**
 - OS: ubuntu
 - Version : 18

**Comment by pheel** [comment]
Hi @sanjaykhanssk thanks for the report. Can you try cloning your project to a different name, i.e. not `bot_front`, and let us know if it helps?

**Comment by znat** [comment]
Hi @sanjaykhanssk here how we generally solve it:
```
botfront killall
botfront up
```

If it does not work:
```
botfront killall
docker stop 24d46db7b2a311f6d1be7d322df8366571d25b425851a6c387a2753329db40b7
docker rm 24d46db7b2a311f6d1be7d322df8366571d25b425851a6c387a2753329db40b7
botfront up
```

Let us know

**Comment by sanjaykhanssk** [comment]
root@moonproduct:/home/ssk/bots/bot_front# docker stop 24d46db7b2a311f6d1be7d322df8366571d25b425851a6c387a2753329db40b7
Error response from daemon: No such container: 24d46db7b2a311f6d1be7d322df8366571d25b425851a6c387a2753329db40b7
root@moonproduct:/home/ssk/bots/bot_front# docker rm 24d46db7b2a311f6d1be7d322df8366571d25b425851a6c387a2753329db40b7

**Comment by znat** [comment]
Is the issue persisting or were you able to start botfront?

**Comment by sanjaykhanssk** [comment]
no i'm not able to start botfront , when i execute **botfront up** this error only showing

**Comment by znat** [comment]
What does `docker ps -a` return?

**Comment by sanjaykhanssk** [comment]
(base) ssk@ssk:~/bots/bot_front$ sudo docker ps -a
```
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS              PORTS                    NAMES
535bac1cf011        rasa/rasa-sdk:1.3.2        "./entrypoint.sh sta…"   43 seconds ago      Up 33 seconds       0.0.0.0:5055->5055/tcp   botfront-actions
f35ebede62a4        botfront/duckling:latest   "/bin/sh -c 'stack e…"   43 seconds ago      Up 32 seconds       0.0.0.0:8000->8000/tcp   botfront-duckling
087549cc7034        mongo:latest               "docker-entrypoint.s…"   2 days ago          Created                                      botfront-mongo

```

**Comment by znat** [comment]
Right. So you can remove them either by their name or I'd: `docker rm 535bac1cf011 f35ebede62a4 087549cc7034`

**Comment by sanjaykhanssk** [comment]
**steps i did:**
 
`(base) ssk@moonproduct:~/bots/bot_front$ sudo docker stop 535bac1cf011 f35ebede62a4 087549cc7034
`

```
`sudo docker ps -a

CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS                            PORTS               NAMES
535bac1cf011        rasa/rasa-sdk:1.3.2        "./entrypoint.sh sta…"   About an hour ago   Exited (137) About a minute ago                       botfront-actions
f35ebede62a4        botfront/duckling:latest   "/bin/sh -c 'stack e…"   About an hour ago   Exited (137) About a minute ago                       botfront-duckling
`
```
`sudo docker rm 535bac1cf011 f35ebede62a4 087549cc7034
`

**But it fails** 
```
(base) ssk@ssk:~/bots/bot_front$ sudo botfront up
✖ Couldn't start Botfront. Retrying in verbose mode...
⠏ Starting Botfront...Creating network "bot_front_botfront-network" with the default driver
⠸ Starting Botfront...Creating volume "bot_front_botfront-db" with default driver
Starting botfront-mongo    ... error
Creating botfront-actions ... 
Creating botfront-duckling ... 
⠹ Starting Botfront...
Creating botfront-actions  ... done
Creating botfront-duckling ... done
⠋ Starting Botfront...
ERROR: for mongo  Cannot start service mongo: network cae89c3eb961b57e85207fcb2799edcb6da770d7f102337aa139c4de409dba5d not found
Encountered errors while bringing up the project.
✖ ERROR: Something went wrong. Check the logs above for more information ☝️, or try inspecting the logs with botfront logs.

```

**Comment by znat** [comment]
Hey @sanjaykhanssk , were you able to solve the issue?

**Comment by sanjaykhanssk** [comment]
No, I have re-installed my OS because of some error, after re-installed I haven't installed the bot front , but it works in my teammate laptop he also using the same OS.
