### ISSUE TITLE
Action server does not register custom actions

### ISSUE THREAD

**Issue by gothax** [botfront/botfront#37]
I just added a custom action as explained in the tutorial, but rasa_core_sdk (action server) does not register my new action (file saved, rebuild, restart container..)

./actions
-/custom_actions
--/__init__.py
`class ActionFAQ(Action):

    def name(self):
        return 'action_faq'`
-> OK
--/my_actions.py
`class GuestsAction(Action):

    def name(self):
        return 'action_guests'`
-> Not registered (see screenshot) https://imgur.com/0I6xspD

All imports are done.

Do you have any idea what's the problem ?

Thank you.

**Comment by znat** [comment]
@gothax is your file in the custom_actions folder? What is your OS?

**Comment by gothax** [comment]
@znat Yeah, i'm actually working on a MAC, but using Docker's containers.
https://imgur.com/QDLZXHh

**Comment by znat** [comment]
Sometimes the logs are not contiguous, e.g. you might find your other registration further. Or... Did you run the watch script?
If none of the above works, the quick workaround is to move the code in my_action to __init__

**Comment by znat** [comment]
@gothax did the above help?

**Comment by gothax** [comment]
@znat Nothing is happening when i try to call my custom action from the bot (even if it's declared on domain & stories).

When i create a custom action in __init__.py, it works. (The log register it).

Should i import  "custom_actions".py in the init.py to separate the differents custom actions in many files ?

The init is probably the only file which is imported and executed when rasa_core is reloading, no ?

Thanks for your help.

**Comment by znat** [comment]
@gothax dis you run the watch script? (https://docs.botfront.io/guide/getting-started/rasa-stack.html#prepare-your-environment). It rebuilds the actions container on every change. 

>Nothing is happening when i try to call my custom action from the bot (even if it's declared on domain & stories).
You should.ar least see an error I'm the logs for calling an action that does not exist)

**Comment by gothax** [comment]
@znat I didnt run the watch script, but for now it works when i add actions to __init__file.

My problem is solved.
