### ISSUE TITLE
Botfront Installation Not Working On Windows 10 Home

### ISSUE THREAD

**Issue by kellog5** [botfront/botfront#370]
**Describe the bug**
- botfront init fails with error: Error: Command failed: docker   info
- It appears the docker info cmd in the docker-cli-js module fails because the machine name is not passed through as an option

**To Reproduce**
1. Install and configure docker 
2. Install botfront (npm install -g botfront)
3. Initialize botfront (botfront init)

**Expected behavior**
Botfront is initialized and project creation is started

** Detailed Error Message **
│ERROR: error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/info: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.│
│' stderr = 'errors pretty printing info  

**Desktop (please complete the following information):**
 - OS: Windows 10 Home (not currently supported)
 - Browser [chrome]
- Docker Toolbox (Docker for windows not supported on Windows 10 Home)

**Additional context**
- I can successfully connect to a docker-machine and run docker info from powershell
- If I run botfront init from the same powershell I get the error
- I have removed and re-created the docker-machine multiple times
- The error seems to occur when the verifySystem() function in utils.js attempts to call docker info by using the docker-cli-js module
    const docker = new Docker();
    const result = await docker.command('info');
- I created a test js file that was able to successfully call the docker info command by passing in the docker-machine name "default" (which I used during docker setup)
    const options = new Options("default")
    const docker = new Docker(options)
    const result = await docker.command("info")
- It appears that the docker.command('info) function removes all environment variables and only users variables passed through the cmd (expected).  The docker info command needs variables (like DOCKER_HOST, DOCKER_CERT_PATH ...) which are stored in environment variables and fails if they are not available.  The docker-cli-js module handles this by calling docker config to add these variables to the cmd line.  The module only does this IF the machine name is passed through the docker constructor as an option. (index.js within docker-cli-js)
            if (docker.options.machineName) {
                const dockerMachine = new dockermachine_cli_js_1.DockerMachine();
                return dockerMachine.command("config " + docker.options.machineName).then(function (data) {
                    //console.log('data = ', data);
                    machineconfig = data.machine.config;
                });
            }

Proposed Solution:
- add a flag option to botfront init that allows the machine name to be passed through
- e.g., botfront init -m default
- In this case the machine name (default) would be used to create an options object and used in the constructor of the docker object in the verifySystem() function in utils.js    

Disclaimer
My initial assessment my very well be completely off as I am installing this for the first time on a platform (Windows 10/Docker Toolbox) that is not supported.  If so, please let me know of any fix to get botfront working on this platform.  

Looking forward to seeing what botfront can do.

Thanks in advance.

**Comment by pheel** [comment]
See https://github.com/botfront/botfront/issues/370
