### ISSUE TITLE
Documentation for canonical examples

### ISSUE THREAD

**Issue by engahmed1190** [botfront/botfront#375]
**Canonical examples Documentation**

I hope we can have a section for canonical examples and how to use them.

**Comment by akarsh1995** [comment]
By the way any idea how to use them ?

**Comment by znat** [comment]
Hi, thanks for asking :)
Canonical examples are examples that give the best idea of the intent meaning.
In the OS edition, it's mainly used to define which NLU example appear in stories and to avoid less meaningful examples used to enrich learning.
We also plan on using them in an improved disambiguation policy
At the moment, canonical examples are used in stories. If a canonical example is used
