### ISSUE TITLE
Upgrade to the new combined Rasa package + Rasa X

### ISSUE THREAD

**Issue by amitbend** [botfront/botfront#38]
Rasa recently announced version 1.0 of the combined Rasa package, so Rasa core & NLU will be available in the same package and further development will be done on this package. 

You can look at the full announcement [here](https://blog.rasa.com/algorithms-alone-wont-solve-conversational-ai-introducing-rasa-x/)

As a feature request, I suggest updating the project to use the new Rasa package. what do you think?

**Comment by MatthieuJnon** [comment]
We're currently working on it !

**Comment by amitbend** [comment]
Hey guys, do you know already when you're planning to release the new version?
I see new commits every day, and I'm excited to try it out and upgrade the current version

**Comment by znat** [comment]
Done
