### ISSUE TITLE
Application fails after login while running in Kubernetes

### ISSUE THREAD

**Issue by paulyhedral** [botfront/botfront#386]
**Describe the bug**
Javascript errors when trying to access the application (see below). Installed in Kubernetes 1.14 on AWS EKS.  The application seems to work fine when running from a local installation using Docker Compose, but running in a proper production context, it fails to work at all.

**To Reproduce**
1. Setup application in Kubernetes with load balancer and SSL certificate.
2. Go to 'https://botfront.example.com'
3. Login using credentials provided when setting up application.

**Expected behavior**
Project page appears and behaves normally.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Kubernetes 1.14
 - Browser: Chrome or Firefox (latest version of either)
 - Version: v0.18.5

**Additional context**
```
Exception from Tracker recompute function: 
TypeError: a[0] is undefined 
d/this.route/<@https://botfront.<redacted>/36223bee37f42f95a67a69e17882f7d35e1839de.js?meteor_js_resource=true:153:303233
_compute@https://botfront.<redacted>/36223bee37f42f95a67a69e17882f7d35e1839de.js?meteor_js_resource=true:47:2321
t@https://botfront.<redacted>/36223bee37f42f95a67a69e17882f7d35e1839de.js?meteor_js_resource=true:47:1452
tracker.js/s.autorun@https://botfront.<redacted>/36223bee37f42f95a67a69e17882f7d35e1839de.js?meteor_js_resource=true:47:3998
d/this.route@https://botfront.<redacted>/36223bee37f42f95a67a69e17882f7d35e1839de.js?meteor_js_resource=true:153:302997
componentDidUpdate@https://botfront.<redacted>/36223bee37f42f95a67a69e17882f7d35e1839de.js?meteor_js_resource=true:153:303419
ss@https://botfront.<redacted>/36223bee37f42f95a67a69e17882f7d35e1839de.js?meteor_js_resource=true:9:835072
us@https://botfront.<redacted>/36223bee37f42f95a67a69e17882f7d35e1839de.js?meteor_js_resource=true:9:836592
el/<@https://botfront.<redacted>/36223bee37f42f95a67a69e17882f7d35e1839de.js?meteor_js_resource=true:9:849715
scheduler.production.min.js/t.unstable_runWithPriority@https://botfront.<redacted>/36223bee37f42f95a67a69e17882f7d35e1839de.js?meteor_js_resource=true:9:879167
el@https://botfront.<redacted>/36223bee37f42f95a67a69e17882f7d35e1839de.js?meteor_js_resource=true:9:849648
Zs@https://botfront.<redacted>/36223bee37f42f95a67a69e17882f7d35e1839de.js?meteor_js_resource=true:9:849424
Ys@https://botfront.<redacted>/36223bee37f42f95a67a69e17882f7d35e1839de.js?meteor_js_resource=true:9:848771
Ks@https://botfront.<redacted>/36223bee37f42f95a67a69e17882f7d35e1839de.js?meteor_js_resource=true:9:847790
ys@https://botfront.<redacted>/36223bee37f42f95a67a69e17882f7d35e1839de.js?meteor_js_resource=true:9:846603
enqueueForceUpdate@https://botfront.<redacted>/36223bee37f42f95a67a69e17882f7d35e1839de.js?meteor_js_resource=true:9:798686
react.production.min.js/A.prototype.forceUpdate@https://botfront.<redacted>/36223bee37f42f95a67a69e17882f7d35e1839de.js?meteor_js_resource=true:9:737532
calculateData/this.computation</<@https://botfront.<redacted>/36223bee37f42f95a67a69e17882f7d35e1839de.js?meteor_js_resource=true:85:1807
_compute@https://botfront.<redacted>/36223bee37f42f95a67a69e17882f7d35e1839de.js?meteor_js_resource=true:47:2321
_recompute@https://botfront.<redacted>/36223bee37f42f95a67a69e17882f7d35e1839de.js?meteor_js_resource=true:47:2476
tracker.js/s._runFlush@https://botfront.<redacted>/36223bee37f42f95a67a69e17882f7d35e1839de.js?meteor_js_resource=true:47:3485
a@https://botfront.<redacted>/36223bee37f42f95a67a69e17882f7d35e1839de.js?meteor_js_resource=true:1:3083
```

**Comment by znat** [comment]
Hi @paulyhedral , we have a lot of successful experience deploying on Kubernetes. On GKE though, but I don't think it makes a difference.
A very common source of error is a wrong [`ROOT_URL`](https://botfront.io/docs/deployment/installation/#environment-variables) setting. Can you confirm that yours is ok?

**Comment by Cherchercher** [comment]
@znat on chrome it goes to /404 with the following error: 
 Exception from Tracker recompute function:
36223bee37f42f95a67a69e17882f7d35e1839de.js?meteor_js_resource=true:1 TypeError: Cannot read property '_id' of undefined
    at 36223bee37f42f95a67a69e17882f7d35e1839de.js?meteor_js_resource=true:153
    at t._compute (36223bee37f42f95a67a69e17882f7d35e1839de.js?meteor_js_resource=true:47)
    at new t (36223bee37f42f95a67a69e17882f7d35e1839de.js?meteor_js_resource=true:47)
    at Object.s.autorun (36223bee37f42f95a67a69e17882f7d35e1839de.js?meteor_js_resource=true:47)
    at d.route (36223bee37f42f95a67a69e17882f7d35e1839de.js?meteor_js_resource=true:153)
    at d.componentDidUpdate (36223bee37f42f95a67a69e17882f7d35e1839de.js?meteor_js_resource=true:153)
    at ss (36223bee37f42f95a67a69e17882f7d35e1839de.js?meteor_js_resource=true:9)
    at us (36223bee37f42f95a67a69e17882f7d35e1839de.js?meteor_js_resource=true:9)
    at 36223bee37f42f95a67a69e17882f7d35e1839de.js?meteor_js_resource=true:9
    at Object.t.unstable_runWithPriority (36223bee37f42f95a67a69e17882f7d35e1839de.js?meteor_js_resource=true:9)

**Comment by znat** [comment]
`Tracker recompute function` are low meaningless low level errors
Anything else in the console? Have you tried `botfront logs` to see if `botfront-app` throws an error? Are you also on a K8S setup?

**Comment by paulyhedral** [comment]
This error appears in the botfront pod logs right after application startup:
```
(node:1) UnhandledPromiseRejectionWarning: Error: Cannot find module './globalSettings.schema.kubernetes'
    at makeMissingError (packages/modules-runtime.js:222:12)
    at Module.resolve (packages/modules-runtime.js:228:17)
    at Promise.then.toBeFetched (packages/modules-runtime.js:154:31)
    at new Promise (<anonymous>)
    at Module.prefetch (packages/modules-runtime.js:153:34)
    at Module.dynamicImport (packages/dynamic-import.js:460:17)
    at globalSettings.collection.js (imports/api/globalSettings/globalSettings.collection.js:22:1)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/opt/bundle/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime/index.js:38:38)
    at project.collection.js (imports/api/project/project.collection.js:1:306)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/opt/bundle/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime/index.js:38:38)
    at scopes.js (imports/lib/scopes.js:1:182)
    at fileEvaluate (packages/modules-runtime.js:336:7)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```

**Comment by paulyhedral** [comment]
Also, I'm fairly certain the `ROOT_URL` is correct. It's supposed to point to the external entry for the application, correct?

**Comment by znat** [comment]
Oh now I see. you have set `orchestrator` to `kubernetes`.
The OSS version only supports `docker-compose` as `orchestrator` value.  So you must just **not** set it.
Then you'll be able to adjust settings and make it work.

**Comment by znat** [comment]
Hi @paulyhedral  is this resolved?

**Comment by Cherchercher** [comment]
The issue is resolved
