### ISSUE TITLE
Mongodb authent with botfront-ui

### ISSUE THREAD

**Issue by gothax** [botfront/botfront#39]
Hello,

When i launch botfront as a container, it launch entrypoint.sh 

First, you can note that you must set a chmod +x /docker/entrypoint.sh  to execute it on build.

Second, I want to connect botfront-ui with my mongodb database, which have authentication enabled.

I tried two things : 

1 :  Authent in url
ENV VAR
MONGO_URL = mongodb://admin:!(3+y6<H!GJAd{6W@mongo-db:27017/meteor

But it does nothing. When i set authent on uri, it stay at 
"23/05/2019 09:29:29Connecting to MongoDB..."

2 : No authent specified
ENV VAR
MONGO_URL = mongodb://mongo-db:27017/meteor

Now, botfront-ui connnect well to the database, but have no permissions...

This is the code in entrypoint.sh which do the check for connect to mongodb, right ?
`node <<- 'EOJS'
require('p-wait-for')(function() {
	return new Promise(function (resolve, reject) {
		require('mongodb').MongoClient.connect(process.env.MONGO_URL, function(err, client) {
			const successfullyConnected = err == null;
			if (successfullyConnected) {
				client.close();
				process.exit(0);
			} else {
				if(client) {
					client.close();
				}
				resolve(false);
				return;
			}
			resolve(successfullyConnected);
		});
	});
}, 10000);
EOJS`

**Comment by znat** [comment]
Hey @gothax, my first guess is you need to specify an authentication database in your query string

**Comment by gothax** [comment]
Hello @znat  !

I removed the authentication from my database.
It's too complicated to implement this actually, i don't really understand the global process.. ;) 
For sure, If i set my mongodb://username:password@hostname:PORT on MONGO_URL VAR ENV, it doesn't work. My  container never find my mongo-db database. 

(I tested the string with 'mongo mongodb:// ....' and it works)

You can close it, but i think it can be a new feature to read uri with id:password :)

**Comment by znat** [comment]
@gothax, authentication in mongodb string works. Usually you need to specify the authentication database, usually by appending something like `?authSource=admin` to your string
