### ISSUE TITLE
Responses are deleted when added to a story by md

### ISSUE THREAD

**Issue by kenrilea** [botfront/botfront#408]
**Describe the bug**
responses created in the bot responses page are sometimes deleted when added to a story via md.

**To Reproduce**
note: the behaviour is inconsistent, sometimes the response is deleted, other-times it works normally.

1. create a response via the bot responses page
2. use the md editor to add the response to a story
3. toggle to the visual editor
result:  the response shows utter_response_name, and does not exist in the bot responses page

**Expected behavior**
the response created in the bot responses page is added to the story.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: IOS
 - Browser chrome
 - 76

**Additional context**
possibly related to responses being deleted when they do not exist in a story.

**Comment by pheel** [comment]
@kenrilea Is this still valid?
