### ISSUE TITLE
How to add a new entity in the NLU menu

### ISSUE THREAD

**Issue by rmiaouh** [botfront/botfront#441]
![Fd](https://user-images.githubusercontent.com/43033520/72669262-c3bc6880-3a2f-11ea-94a1-9cb3f0fc68dc.png)

I don't understand why i can't add a new entity ( i can only add a new intent) Can someone know why ?

(linux - botfront 0.9)

**Comment by znat** [comment]
Yes, we have a bug there. You can easily add entities directly in the table after you add the example

**Comment by rmiaouh** [comment]
![fd2](https://user-images.githubusercontent.com/43033520/72669478-5eb64200-3a32-11ea-856c-5c1223be82cc.png)

Oh thank you, so yes i had to add the example. Then i can select the text and the menu appear, thank you for all Znat :)

**Comment by rmiaouh** [comment]
> ![fd2](https://user-images.githubusercontent.com/43033520/72669478-5eb64200-3a32-11ea-856c-5c1223be82cc.png)
> 
> Oh thank you, so yes i had to add the example. Then i can select the text and the menu appear, thank you for all Znat :)



> Yes, we have a bug there. You can easily add entities directly in the table after you add the example. Just select the text and a menu will appear
@znat ty for all
