### ISSUE TITLE
Response editing showing wrong response name

### ISSUE THREAD

**Issue by GeovanaRamos** [botfront/botfront#447]
**Describe the bug**
After importing a project with some responses, if you create a new one and try to edit it, the response editor will show wrong response name.

**To Reproduce**
1. Import some responses
2. Create a new one
3. Edit the new one
4. Wrong response name on editor

**Expected behavior**
Response editor should show the response name that was selected

**Screenshots**
Clicked on "utter_test" and editor shows correct text but wrong name (utter_acessar_curso)
![image](https://user-images.githubusercontent.com/31005087/73065155-9d5c5a00-3e81-11ea-8f4b-96ff22949e70.png)

**Additional context**
Botfront 0.19.0

**Comment by dcsan** [comment]
so you think it's just an indexing problem?
is it always off in the same direction vs. another list?

**Comment by GeovanaRamos** [comment]
I found out that it happens after you search for an utter, but it seems [this pr](https://github.com/botfront/botfront/pull/465) fixed it. I didn't test it yet
