### ISSUE TITLE
Wrong server address on production leads to failure on some features

### ISSUE THREAD

**Issue by amitbend** [botfront/botfront#47]
I've tried to deploy a bot to a server, but some of the functionality does not work ("try out your bot", "advanced settings")

On the console I can see:
`Failed to load resource: net::ERR_CONNECTION_REFUSED`
and the address is `http://localhost:8888/__meteor__/dynamic-import/fetch`
which probably should have been the ip of the server instead of `localhost`

**Comment by znat** [comment]
Have you followed the instructions here? https://docs.botfront.io/guide/deployment/

**Comment by amitbend** [comment]
@znat Hey, I've used the docker compose (botfront-starter) version

**Comment by znat** [comment]
Still, have you set the environment variables? I'm botfront-starter they're all in local.env

**Comment by amitbend** [comment]
I did not. I'll do it and let you know.
Maybe it's worth to add a comment in the docs
