### ISSUE TITLE
meteor dependency

### ISSUE THREAD

**Issue by dcsan** [botfront/botfront#487]
I was reading up on this project, and it looks great but I was wondering what your plans are to move off meteor?

I used to use it myself a lot but since MDG have divested the project, it seems dead. that would limit others from putting in work to this project I think...

**Comment by znat** [comment]
We're progressively moving to a std graphql stack, but Meteor was acquired recently and development has restart

**Comment by dcsan** [comment]
ok thanks for the info. I guess it doesn't matter so much for the authoring tool (and meteor was revolutionary in it's time).
