### ISSUE TITLE
cannot build docs

### ISSUE THREAD

**Issue by dcsan** [botfront/botfront#489]
**Describe the bug**
following instructions here
https://github.com/botfront/botfront#quick-start
I was unable to build the docs

**To Reproduce**
check out the repo
```
docker build -t botfront/botfront-docs botfront/docs
```

gives error:
> unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /Users/dcollier/dev/rnd/botfront/botfront/docs/Dockerfile: no such file or directory

**Expected behavior**
be able to build the docs container

**Desktop (please complete the following information):**
```
Mac OS 10.15.3

$ docker -v
Docker version 19.03.5, build 633a0ea

```

**Additional context**
this is *after* I have pulled down and built the docker image for botfront itself, in case that's relevant.

**Comment by znat** [comment]
Oups. We need to update our docs. We don't provide a way to build the docs
anymore
