### ISSUE TITLE
package.json doesn't exist?

### ISSUE THREAD

**Issue by dcsan** [botfront/botfront#491]
**Describe the bug**
Following install steps here
https://github.com/botfront/botfront#installation

**To Reproduce**
install meteor
build the container
get the container running

exec
`meteor npm run start:docker-compose.dev`

gives error:
```
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /Users/dcollier/dev/rnd/rascal/bf2/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/Users/dcollier/dev/rnd/rascal/bf2/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dcollier/.npm/_logs/2020-02-26T21_25_35_708Z-debug.log
```

and indeed there is no such `package.json` created

**Expected behavior**
can get started.

** env **
latest docker, macos

**Comment by znat** [comment]
You must run nom start from the botfront folder
