### ISSUE TITLE
is linking stories actually working?

### ISSUE THREAD

**Issue by dcsan** [botfront/botfront#500]
This isn't so much of a technical bug, as an issue with how RASA stories work and how to debug with botfront.

I have a story which uses the "link" feature but it doesn't seem to "navigate" to the new story.

![Screen Shot 2020-02-29 at 3 04 02 PM](https://user-images.githubusercontent.com/514002/75616377-f4022700-5b04-11ea-8273-246cb9671b70.png)

and the related `setup` story:

![Screen Shot 2020-02-29 at 3 08 23 PM](https://user-images.githubusercontent.com/514002/75616416-6246e980-5b05-11ea-9c5a-e29ba9082da1.png)

**Comment by dcsan** [comment]
the setup intent is detected, but the linked conversation does not flow.
I could imagine the second bot utterance `is that right` might not get triggered, 
but would think the reception of `basics.yes` would trigger the story to continue.

**Comment by dcsan** [comment]
checking `botfront logs` it seems the fallback policy is being used

```
 rasa.core.processor  - Received user message 'yes' with intent '{'name': 'basics.yes', 'confidence': 0.9903191328048706}' and entities '[]'
 rasa.core.processor  - Logged UserUtterance - tracker now has 12 events.
 rasa.core.policies.fallback  - NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
 rasa.core.policies.memoization  - Current tracker state [{'prev_action_listen': 1.0, 'intent_get_started': 1.0}, {'prev_utter_NahGlWNw': 1.0,
p_phone': 1.0}, {'prev_utter_oREp2ekS': 1.0, 'intent_setup_phone': 1.0}, {'prev_action_listen': 1.0, 'intent_basics.yes': 1.0}]
 rasa.core.policies.memoization  - Launch DeLorean...
 rasa.core.policies.memoization  - Current tracker state [None, None, None, {}, {'prev_action_listen': 1.0, 'intent_basics.yes': 1.0}]
 rasa.core.policies.memoization  - There is no memorised next action
 rasa.core.policies.memoization  - Current tracker state [{'prev_action_listen': 1.0, 'intent_get_started': 1.0}, {'prev_utter_NahGlWNw': 1.0,
p_phone': 1.0}, {'prev_utter_oREp2ekS': 1.0, 'intent_setup_phone': 1.0}, {'prev_action_listen': 1.0, 'intent_basics.yes': 1.0}]
 rasa.core.policies.memoization  - There is no memorised next action
 rasa.core.policies.ensemble  - Predicted next action using policy_0_FallbackPolicy
 rasa.core.processor  - Predicted next action 'action_default_fallback' with confidence 0.30.
 rasa_addons.core.nlg.graphql  - Requesting NLG for utter_default from http://botfront:3000/graphql.
 sgqlc.endpoint.http  - Query:

```

**Comment by dcsan** [comment]
I looked into the exported story files
and it looks like the labeled branch is just refering to itself in each case, not to the branch it should include / link to?

ie in no case does `get_started` story . branches link to the `setup` story?

Is this a bug in the exporter? Or how botfront internally models the conversation data?

```
# Intro stories

## Get started
* get_started
  - utter_NahGlWNw
> Get_started__branches

## Get started__setup-phone
> Get_started__branches
* setup_phone
  - utter_oREp2ekS

## Get started__other
> Get_started__branches
* random
  - utter_y1Ra8s0k

## Get started__chitchat
> Get_started__branches
* greeting
  - utter_Xch7Oq2D

## Get started__joke
> Get_started__branches
* ask_joke
  - utter_zhBT9KMO

```  

```
# setup

## setup
  - utter_IZXAtrSA
> setup__branches
## setup__yes
> setup__branches
* basics.yes
  - utter_UApYQ-It
## setup__no
> setup__branches
* basics.no
  - utter_Ds_rRtP1

```

**Comment by dcsan** [comment]
when I looked at the same export in botfront JSON format I don't see any links, maybe that feature isn't supported in the exporter?

![image](https://user-images.githubusercontent.com/514002/75616516-dd5ccf80-5b06-11ea-9d5b-3ee052110010.png)

**Comment by znat** [comment]
Yes, it is. And in 0.20 there's a Rasa importer that will also get branches and links from projects exported for rasa

**Comment by dcsan** [comment]
OK it could be my misunderstanding how rasa branches work. I only see self-referencing branches in the exports above. There is no way that the other story is linked to.

I tried hand modifying and re-importing but

```
## Get started__setup-phone
> Get_started__branches
* setup_phone
  - utter_oREp2ekS
> setup__branches
```

![image](https://user-images.githubusercontent.com/514002/75616708-8dcbd300-5b09-11ea-910f-85e53105ea99.png)

I find rasa checkpoints confusing

you have to put the **link** at the top of the branch, not where you want it to run.
like where you want to include it?
not at the point where you want it to link from?

I think it's their philosophy to not run a state machine but to run the whole conversations from ML predictions. So I think the checkpoints are just used like pre-processor flags to basically "include"  / inline expansion of some content before passing to the trainer. Not sure though.

https://rasa.com/docs/rasa/core/stories/#checkpoints

I'll try messing around directly with the `.md` files and `rasa train`

**Comment by znat** [comment]
Hi,
Can you please share your export files here (both rasa and botfront)?
Also the file giving you the error?
Thanks!

I can confirm that linking works on the latest release.

**Comment by dcsan** [comment]
I started working on a very simple example with linked stories just in RASA itself, and they completely do not work the way I thought... I'm trying to understand the logic and create a simple example. It's probably the case that your system is just using RASA logic.

basically you cannot link > to a story and then expect the NLU to continue. I'm not quite sure what this feature is doing... >.<

**Comment by znat** [comment]
May be you could paste de stories you are trying to link?

**Comment by dcsan** [comment]
https://forum.rasa.com/t/checkpoints-how-they-work-with-graphs/25835

I posted on the forum about it here. I think checkpoints seem to be pretty much unusable as is. 
https://forum.rasa.com/t/checkpoints-how-they-work-with-graphs/25835

I guess you have a lot of experience building bots with rasa, as well as this wonderful editing tool. But putting the link feature at the bottom of one story in your UI I think is gonig to confuse people as I don't think that's how checkpoints work; since that is where you **define** them, not link to or use them... at least as far as I can understand. But as I said... either I'm missing something or this feature is really half-baked.

**Comment by dcsan** [comment]
FWIW I put the scripts etc. for the bot here
https://github.com/dcsan/rasa-test/blob/master/bots/barbot/data/stories.md

this was just hand scripted not using botfront, but the point stands.

**Comment by pheel** [comment]
@dcsan From the point of view of Rasa, this is the story this ends up being equivalent to:

``## tell joke ++ asked joke
- utter_joke
* greet
- utter_greet
- utter_goodbye``

Also, the error you got above by importing your file are due to not following the Botfront branching convention: the story is called `Get started__setup-phone` but its branch-out checkpoint is called `setup__branches`; it should be `Get started__setup-phone__branches`.

**Comment by dcsan** [comment]
@pheel thanks! so

```
## asked joke
> telljoke
* greet
- utter_greet
- utter_goodbye

## tell joke
- utter_joke
> telljoke
```

becomes
```
## tell joke ++ asked joke
- utter_joke
* greet
- utter_greet
- utter_goodbye
```

**Comment by dcsan** [comment]
in this case where the checkpointed story does have a intent 

![image](https://user-images.githubusercontent.com/514002/76262242-05d87e00-6219-11ea-9e21-71a3f05ab581.png)

![image](https://user-images.githubusercontent.com/514002/76262260-14bf3080-6219-11ea-9a0e-7ecb4d8a937d.png)


this story works and gets expanded:

```
## asked joke
> telljoke
- utter_goodbye
```

but this one does not:
```
## hello goodbye
* greet
  - utter_greet
> telljoke
* goodbye
  - utter_goodbye
```

so it seems the `checkpoint`ed content has to be at the very start of a sequence....

**Comment by pheel** [comment]
That's right. The Rasa checkpoint syntax works that way. Botfront does raise an error when you try to import that kind of story, cf. your previous screenshot about "sandwiching". :) Feel free to reopen the issue if needed.

**Comment by dcsan** [comment]
sure it's fine to close it, not an _error_ with botfront, but i think you can see why the UI with 

"link to story -> "

is a bit confusing? it does imply some type of routing to the next story.
