### ISSUE TITLE
domain file updates

### ISSUE THREAD

**Issue by dcsan** [botfront/botfront#501]
training rasa on some BF exported data i see these errors reported:

> /Users/dcollier/dev/rnd/rascal/rasa/venv/lib/python3.7/site-packages/rasa/core/domain.py:133: FutureWarning: Your domain file contains the key: 'templates'. This has been deprecated and renamed to 'responses'. The 'templates' key will no longer work in future versions of Rasa. Please replace 'templates' with 'responses'
  return cls.from_dict(data)

> /Users/dcollier/dev/rnd/rascal/rasa/venv/lib/python3.7/site-packages/rasa/core/domain.py:151: FutureWarning: No tracker session configuration was found in the loaded domain. Domains without a session config will automatically receive a session expiration time of 60 minutes in Rasa version 2.0 if not configured otherwise.
  session_config = cls._get_session_config(data.get(SESSION_CONFIG_KEY, {}))

**Comment by pheel** [comment]
First warning fixed in upcoming release.
