### ISSUE TITLE
support named utterances

### ISSUE THREAD

**Issue by dcsan** [botfront/botfront#502]
as [discussed here on spectrum](https://spectrum.chat/botfront/feature-requests/responses-naming~db124fc4-7773-4a16-866b-e7b2d2853429) it would be convenient to use named utterances for bot talk.

while it's nice to just type out text inline, having some management of utterances makes things like debugging easier.

it feels natural to have a "choose utterance" on the dropdown here ^
and that would lead to a different input form that would allow you to typeahead and choose an utterance from a list. maybe you guys have a better plan?

![image](https://user-images.githubusercontent.com/514002/75617271-cbccf500-5b11-11ea-85f0-76cbca7d791c.png)

**Comment by dcsan** [comment]
this is what I get from a visualization of a botfront built conversation:

![image](https://user-images.githubusercontent.com/514002/75617253-611bb980-5b11-11ea-828a-b68b6fce6e07.png)

**Comment by dcsan** [comment]
however it's definitely annoying if you have to always setup your `utter`s first

perhaps we can have a method where you just type in the utterance name and BF would create a placeholder? then you can add the details later.
Or the utterance could be named as a sanitized (and checked to be unique) version of the plain text?

bot: How's it going today?

creates:

```
- utter_hows_it_going_today_v1
  text: How's it going today?
```

and creates the needed actions at export time.

**Comment by znat** [comment]
It's true that we could use a sanitize version capped to a certain length and concatenate it with a short_id to guarantee uniqueness. But it would only be 100% useful if changing the content would change the response name as well, which makes the task much more difficult

**Comment by dcsan** [comment]
i think it would be a small change to use sanitized names, and really help to get a first pass of "scaffolding out" a conversation. if you do change the text later that might often be because you want to add variations.

re: updating
you mean the problem would be with the UI to change the utterance names? or some other deeper code issue?
you're storing the conversation in mongo tho right? are you using those utterance names as the foreign keys?

**Comment by alebeta90** [comment]
Hi, 

We are also facing similar situation with the utterances, when we need to debug it gets a little bit difficult to visualize the conversation. If we could edit the existent utter or set the utter name before we add the utter text will be great. Also the sanitized names would be maybe the easiest way and still will give us a hint in which part of the conversation the intent belongs to, it is what botsoceity does in their platform.

All the best

**Comment by pheel** [comment]
This feature is now live as of [0.25.2](https://github.com/botfront/botfront/blob/master/CHANGELOG.md#0252-2020-07-14)!
