### ISSUE TITLE
Bot return utter name as message

### ISSUE THREAD

**Issue by alebeta90** [botfront/botfront#529]
**Describe the bug**
when we use the test chat window, the bot returns the utter name instead of the text related to that utter

2020-03-24 16:29:38 DEBUG    rasa.core.processor  - Action 'utter_Zna1OsI67' ended with events '[BotUttered('utter_Zna1OsI67', {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, {"metadata": null}, 1585067378.7234225)]'.

**To Reproduce**
we tested on botfront 0.20.3 and 0.21.3 with rasa 1.7.1

**Expected behavior**
show utter text instead of utter name

**Screenshots**
![image](https://user-images.githubusercontent.com/11571266/77453961-395dff80-6df8-11ea-9e94-69ca7c2b2ae7.png)

here we can see the utter has its text assign

![image](https://user-images.githubusercontent.com/11571266/77454255-92c62e80-6df8-11ea-9df0-568e5f9fa6ac.png)

**Desktop (please complete the following information):**
 - OS: Linux and Windows
 - Browser firefox and chrome

**Comment by znat** [comment]
Is it the same response name when you hover the response in the story?

**Comment by alebeta90** [comment]
I found an interesting behavior when deploying in docker swarm. It seems it is not routing the dns call to the local namespace services, but somehow it is also reaching other services. The some API calls and Rasa calls were going to another botfront instance we have in the cluster.

I will close this issue because it is not related with botfront, or at least it seems not to be.

Thanks for the quick response. 

all the best
