### ISSUE TITLE
rasa_addons.core.channels.messenger.FBmessenger not found

### ISSUE THREAD

**Issue by alebeta90** [botfront/botfront#533]
**Describe the bug**
I was trying to use the channel rasa_addons.core.channels.messenger.FBmessenger to connect to facebook, but it seems to be not present in rasa-for-botfront 1.7.1. I manage to use facebook default channel from Rasa.

**To Reproduce**
Deploy Botfront with Rasa 1.7.1 for botfront, and configure the channel rasa_addons.core.channels.messenger.FBmessenger:

**Expected behavior**
it connects to facebook properly

**Comment by pheel** [comment]
Please try `rasa_addons.core.channels.facebook_messenger.FBMessengerInput` and let us know if that works.

**Comment by alebeta90** [comment]
Perfect I tried and it works

I guess it should be updated in the documentation :D

Thank you
