### ISSUE TITLE
nlu train button get disable after importing botfront project

### ISSUE THREAD

**Issue by engahmed1190** [botfront/botfront#560]
**Describe the bug**
Train Button Disabled at the NLU section while active at Story section 
Moreover, import NLU data redirect to white page

**To Reproduce**
1. Go to 'Setting'
2. Click on .'Import/Export'
2. Click on .'Import'
3. Scroll  to 'Import Botfront Project'
4. Go to 'NLU'
5. See disable train button

**Expected behavior**
Enabled Train Button.

**Screenshots**

![image](https://user-images.githubusercontent.com/25582838/79164679-d00f5200-7de1-11ea-862d-6191ed6dee02.png)

**Comment by pheel** [comment]
@engahmed1190 did you check your instance settings (Settings > Instance)?

**Comment by engahmed1190** [comment]
Thanks. It should be closed
