### ISSUE TITLE
Rasa 1.9.0 and Botfront Tracker Store

### ISSUE THREAD

**Issue by alebeta90** [botfront/botfront#565]
Hi Guys,

It is possible to use the Botfront Tracker Store with rasa-for-botfront:1.9.0 ?

thanks and all the best

**Comment by znat** [comment]
To use 1.9.0 you need to upgrade to 0.22 which comes with a brand new tracker store. Be sure to check the migration guide : https://botfront.io/docs/migration

**Comment by alebeta90** [comment]
thanks @znat 

Maybe in the migration page we should add also the change of the pipeline to use `DIETClassifier` ? or it should be done automatic by the backend?

**Comment by znat** [comment]
We didn't since the DIETClassisfier isn't strictly required. But new projects get initialized with the DIET
