### ISSUE TITLE
Cannot import Botfront project

### ISSUE THREAD

**Issue by marcopeix** [botfront/botfront#588]
**Description**
When I click on Import, and select "Import Botfront project", I upload the project in JSON format and the import fails.

**To Reproduce**
1. Install Botfront on a VM
2. Launch the web interface
3. Follow the basic setup steps
4. Click on Settings, and Import/Export
5. Select "Import Botfront project"
6. Drag and drop the project in JSON format
7. See error: "Import failed"

**Expected behavior**
The project is successfully imported

**Screenshots**
![image](https://user-images.githubusercontent.com/19268689/80819647-58903f80-8ba3-11ea-8a67-c07934e2d307.png)

**Desktop (please complete the following information):**
 - OS: CentOS
 - Chrome
 - Botfront version: 0.18.5

**Comment by pheel** [comment]
@marcopeix If you attach terminal output to the docker logs by doing `botfront logs`, then try importing from the UI, do you get any terminal lines that start with `botfront-api`?

**Comment by marcopeix** [comment]
Yes, I get the following error:
![image](https://user-images.githubusercontent.com/19268689/81098999-31ee4380-8ed8-11ea-836f-dccb969eb78e.png)

**Comment by pheel** [comment]
Botfront-api@0.18.5 used to require your exported file to have the following:

```js
{
    "project": {
        "_id",
        "name",
        "defaultLanguage",
        "nlu_models",
        "templates"
    }
}
```

From 0.19.0 [this requirement is gone](https://github.com/botfront/botfront/commit/92cc5465865a541b4bb92df60373161163db1d0b#diff-25d5b056b669ae5ebacf5f3930c15798R237). If you need to use the 0.18.5 API, you can try adding the missing keys, however if you don't have templates in your backup that probably means your file was exported from a _newer_ version of Botfront, which will not import.

**Comment by pheel** [comment]
All of this points in the direction that backups should specify the version they were exported from, so that earlier versions Botfront don't import backups from later versions with breaking changes.

**Comment by znat** [comment]
@pheel Let's try your solution above @marcopeix well gar back to you. Thanks for your patience

**Comment by znat** [comment]
@pheel re your last comment, we should probably drop the db based export and build up on the rasa one (only project settings and conversations are missing)

**Comment by marcopeix** [comment]
@pheel Thank you for your answer!
In fact, I notice that we do not have the key "templates" in the JSON file. I will try to add the missing key, otherwise I will upgrade the version of Botfront and try to import then.

Thank you @znat for your support! I will keep you posted with my progress!

**Comment by pheel** [comment]
@marcopeix, thanks for pointing out the issue. You will need 0.23 to import that file, which should come out of RC in the next days.

**Comment by marcopeix** [comment]
@pheel  @znat 
Just letting you know that installing upgrading to Botfront 0.23 fixed the issue. I successfully imported the project with the JSON file.

Thank you so much for the support! Really appreciated!
