### ISSUE TITLE
Botfront :MongoError: command listIndexes requires authentication when botfront up is executed

### ISSUE THREAD

**Issue by snehalsabale** [botfront/botfront#602]
I am gettiing error while running botfrontUp command on windows.

**To Reproduce**
1. Install nodejs
2. install docker
3.install mongo db 
4.create c:/data/db directory
5. npm install -g botfront
6. botfront init 
 7.provide folder name i.e projectname
8.cd projectname
9.botfront up

Make below changes in  docker-compose-template.yml

 mongo:
    image: 'mongo:latest'
    container_name: botfront-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: QkKzvVsfRtYs
    networks:
      - botfront-network
    volumes:
      - 'c:/data/db'
    ports:
      - '27017:27017'
    env_file:
      - .env

Expected behavior
Botfront app should run successfully.

Actual behavior is getting error

[36;1mbotfront-app    |[0m 						^
[36;1mbotfront-app    |[0m 
[36;1mbotfront-app    |[0m **MongoError: command listIndexes requires authentication**
[36;1mbotfront-app    |[0m     at /opt/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:581:63
[36;1mbotfront-app    |[0m     at authenticateStragglers (/opt/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/
pool.js:504:16)
[36;1mbotfront-app    |[0m     at Connection.messageHandler (/opt/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connecti
on/pool.js:540:5)
[36;1mbotfront-app    |[0m     at emitMessageHandler (/opt/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/conn
ection.js:310:10)
[36;1mbotfront-app    |[0m     at Socket.<anonymous> (/opt/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/conn
ection.js:453:17)
[36;1mbotfront-app    |[0m     at emitOne (events.js:116:13)
[36;1mbotfront-app    |[0m     at Socket.emit (events.js:211:7)
[36;1mbotfront-app    |[0m     at addChunk (_stream_readable.js:263:12)
[36;1mbotfront-app    |[0m     at readableAddChunk (_stream_readable.js:250:11)
[36;1mbotfront-app    |[0m     at Socket.Readable.push (_stream_readable.js:208:10)
[36;1mbotfront-app    |[0m     at TCP.onread (net.js:601:20)
[34mbotfront-mongo  |[0m 2020-05-19T09:18:39.514+0000 I  NETWORK  [conn88] end connection 172.19.0.6:37068 (1 connection now open)
[36;1mbotfront-rasa   |[0m 2020-05-19 09:18:39 DEBUG    rasa.utils.botfront  - Trying to fetch config from server (retry #1510)
[34mbotfront-app exited with code 1
[0m[36;1mbotfront-rasa   |[0m 2020-05-19 09:18:42 DEBUG    rasa.utils.botfront  - Trying to fetch config from server (retry #1511)
[36;1mbotfront-rasa   |[0m 2020-05-19 09:18:44 DEBUG    rasa.utils.botfront  - Trying to fetch config from server (retry #1512)
[36;1mbotfront-rasa   |[0m 2020-05-19 09:18:46 DEBUG    rasa.utils.botfront  - Trying to fetch config from server (retry #1513)
[36;1mbotfront-rasa   |[0m 2020-05-19 09:18:48 DEBUG    rasa.utils.botfront  - Trying to fetch config from server (retry #1514)
[36;1mbotfront-rasa   |[0m 2020-05-19 09:18:50 DEBUG    rasa.utils.botfront  - Trying to fetch config from server (retry #1515)

getting above errors in log.

**Desktop (please complete the following information):**
 - OS: Windows 10 pro
 - Browser  chrome

**Comment by znat** [comment]
Hi, can you verify that you can use those credentials to connect with Mongo using a regular Mongo client such as Compass?
