### ISSUE TITLE
How to add X-frame-options to botfrontapp

### ISSUE THREAD

**Issue by nhha1602** [botfront/botfront#603]
Dear all,
Could you, please help to help to show me the way to add X-frame-options to botfrontapp?

Thank you.

**Comment by pheel** [comment]
Can you please elaborate on what you want to do?

**Comment by nhha1602** [comment]
Hi,

I want to add this to avoid "Clickjacking" - known as a UI redress attack issue.
To avoid this, we need to add "X-Frame-Options SAMEORIGIN" to the header of http message.

Please advise this.
