### ISSUE TITLE
Additional metadata for training examples

### ISSUE THREAD

**Issue by kearnsw** [botfront/botfront#607]
**Is your feature request related to a problem? Please describe.**
Training a rasa custom component for sentiment analysis jointly with the rest of the rasa ML stack.

**Describe the solution you'd like**
Allow a user to add additional tags to each training example, e.g. sentiment labels. 

**Describe alternatives you've considered**
Off platform, we are using prodigy to do the annotation.

**Additional context**
This support was added in https://github.com/RasaHQ/rasa/pull/5743. In response to this issue, that seems to be the direction the Rasa team is thinking of moving as well: https://github.com/RasaHQ/rasa/issues/5742

**Comment by pheel** [comment]
Hi, we've been thinking about tags/metadata for training data for a while, but never quite got around to implementing it. We've had a single [boolean tag `canonical`](https://github.com/botfront/rasa-addons#note-automatic-generation-of-suggestion-button-titles), but a generalized version is still to come, and would likely have to come with a NLU db overhaul.

Out of curiosity, have you thought of a Markdown notation equivalent for the proposal in https://github.com/RasaHQ/rasa/issues/5742 ?
