### ISSUE TITLE
Regarding Multiple Agent

### ISSUE THREAD

**Issue by Beherasaptami** [botfront/botfront#608]
I have query to ask like is botfront capable of handaling multiple agent

**Comment by pheel** [comment]
@znat Is that in the game plan?

**Comment by znat** [comment]
Hi @Beherasaptami, managing multiple agents and users is a premium feature available in the enterprise edition

**Comment by Beherasaptami** [comment]
Hey @znat if i will go for premium feature can i run multiple agents on same port number
