### ISSUE TITLE
Can you send video attachment not in metadata?

### ISSUE THREAD

**Issue by M-Shadow** [botfront/botfront#609]
Howdy, I'm willing to send a video as an attachment seeing from the docs of rasa-webchat that it can display a video if it receives it as a normal attachment to the response. In Botfront - I've been able to send an attachment with the Custom Format Response - but that only sends it under the metadata section in the "customAttachment" field - which is probably why it isn't displayed in rasa-webchat, as I don't think it reads that stuff from the metadata unless you make a special custom component or a handler for custom messages.

This is how my Custom Format Response looks like:
```yaml
attachment:
  type: video
  payload:
    title: Blank
    src: 'https://youtu.be/8tPnX7OPo0Q'
```
This is how the response of the bot looks when sent:
```json
{
  "event": "bot",
  "timestamp": 1589970849.1438482,
  "metadata": {
    "metadata": null,
    "customText": null,
    "customImage": null,
    "customButtons": null,
    "customElements": null,
    "customAttachment": {
      "type": "video",
      "payload": {
        "title": "Blank",
        "src": "https://youtu.be/8tPnX7OPo0Q"
      }
    }
  },
  "text": null,
  "data": {
    "elements": null,
    "quick_replies": null,
    "buttons": null,
    "attachment": null,
    "image": null,
    "custom": null
  }
}
```

You can look at how rasa-webchat detecs if the response contains a video [here](https://github.com/botfront/rasa-webchat/blob/a6264ca94fb099e3040f9efd24a8ef82db037777/src/components/Widget/msgProcessor.js#L12-L16) and how the check is used to display the video [here](https://github.com/botfront/rasa-webchat/blob/a6264ca94fb099e3040f9efd24a8ef82db037777/src/components/Widget/index.js#L519-L526).

Is there any way to send the attachment without it being in the custom data or metadata, or any other way to send a video as a response that will work with rasa-webchat?

**Comment by pheel** [comment]
Hi @M-Shadow, thanks for reporting. This is definitely a bug. The event should end up as:

```json
{
  "event": "bot",
  "timestamp": 1589970849.1438482,
  "metadata": null,
  "text": null,
  "data": {
    "elements": null,
    "quick_replies": null,
    "buttons": null,
    "attachment": {
      "type": "video",
      "payload": {
        "title": "Blank",
        "src": "https://youtu.be/8tPnX7OPo0Q"
      }
    },
    "image": null,
    "custom": null
  }
}
```

I was able to replicate. I'll keep you updated.

**Comment by pheel** [comment]
Found the problem. Fixed in https://github.com/botfront/rasa-addons/commit/00ca3541d3920d4c1fd71177a3ac5b633d3435fa. Will be part of rasa-for-botfront:v1.9.0-bf.13.

**Comment by pheel** [comment]
Videos are blocked in widget, cf. https://github.com/botfront/botfront/issues/603
<img width="336" alt="Screen Shot 2020-05-20 at 11 01 50 AM" src="https://user-images.githubusercontent.com/759578/82468512-dfdd1e80-9a90-11ea-897a-5fc64649125d.png">
