### ISSUE TITLE
Adding Data bug

### ISSUE THREAD

**Issue by saxh** [botfront/botfront#615]
**Describe the bug**
![Xnip2020-05-26_10-02-43](https://user-images.githubusercontent.com/22788088/82853383-35557780-9f38-11ea-9c4d-099620c97d95.jpg)
![Xnip2020-05-26_10-48-57](https://user-images.githubusercontent.com/22788088/82855689-8f593b80-9f3e-11ea-83dd-275f93633ae1.jpg)
that's my nlu datas.
[nlu.md.zip](https://github.com/botfront/botfront/files/4679521/nlu.md.zip)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pheel** [comment]
See https://github.com/botfront/botfront/issues/600.
