### ISSUE TITLE
Build docker image from botfront source

### ISSUE THREAD

**Issue by nhha1602** [botfront/botfront#616]
Dear all,
I'm new with docker and also botfront.

I tried to build botfront_app images from your source code and get below error.

**docker build -t my_account/botfront_app:1.0 .**

Could you, please advise this.

Even with METEOR_ALLOW_SUPERUSER or --allow-superuser, permissions in your app
directory will be incorrect if you ever attempt to perform any Meteor tasks as
a normal user. If you need to fix your permissions, run the following command
from the root of your project:

  sudo chown -Rh <username> .meteor/local

**Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`**
app/node_modules/semantic-ui-css/semantic.min.css: warn: There are some @import rules in the middle of a file. This might be a bug, as imports are only valid at the beginning of a file.

**Unable to resolve some modules:**

  **"perf_hooks" in /opt/src/imports/api/instances/instances.methods.js
(web.browser)**

If you notice problems related to these missing modules, consider running:

  meteor npm install --save meteor-node-stubs

/docker/build-meteor-bundle.sh: line 11:     8 Killed                  meteor build --directory $APP_BUNDLE_FOLDER --server-only
The command '/bin/sh -c bash $SCRIPTS_FOLDER/build-meteor-bundle.sh' returned a non-zero code: 137

**Comment by pheel** [comment]
This is an out of memory error. You can fix this by [allocating more memory resources to the Docker daemon](https://docs.docker.com/config/containers/resource_constraints/) while building Botfront.
