### ISSUE TITLE
custom default fallback is not working

### ISSUE THREAD

**Issue by c-akhil** [botfront/botfront#619]
**Description**
"utter_default" as text is displaying for end-user,
instead of text set in the bot response for the utter_default

**To Reproduce**
1. Click to 'Responses' in side navigation
2. Click on "Add bot response" button located at top-right
2. Set text in "utter_response_name" as "utter_default"
3. Set any custom fallback text eg:"sorry,what do you mean?" in bot-response-input,
4. Navigate to Stories and train the bot
5. Now chat with bot & Enter some random text for which the bot is not trained
6. Observer the behavior is not modified and "utter_default" is uttered instead of bot-response set 
    for it

**Expected behavior**
custom fallback text set in  bot-response-input for utter_default should uttered instead of 'utter_default'

**Screenshots**
![utter_default](https://user-images.githubusercontent.com/51059452/83199386-b42bf980-a15e-11ea-860a-8ee6f00e2948.png)

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04
 - Browser chrome
 - Version 83.0.4103.61 (Official Build) (64-bit)

**Comment by pheel** [comment]
How are you running Botfront? What do the logs (`botfront logs`) say?

**Comment by znat** [comment]
Hi @c-akhil , what fallback policy did you use? Are other responses working as expected or do you get `utter-...` for everything ? If this is the case the problem is that Rasa can't connect to the NLG server. You can fix that by checkling the logs )`botfront logs` and fixing the NLG in your endpoints
