### ISSUE TITLE
Training of bot getting failed

### ISSUE THREAD

**Issue by c-akhil** [botfront/botfront#620]
**Description**
When started botfront ui locally with "meteor npm run start:docker-compose.dev" as mentioned in "readme.md",and train with some data training gets failed

**To Reproduce**
1. Clone the repo 'https://github.com/botfront/botfront'
2. run "meteor npm install" in the 'botfront/botfront' directory
3. After the installation is complete run 'cd ../cli && npm link'
4. run "botfront init" in a preferred workspace directory
5. run "botfront up -e botfront" ,might take a loger time for 1st usage as to download docker images
6. After the set up is done,in repo directory 'cd ./botfront'  
7. set mongo-db url,project id  eg: 'bf' in package.json (can get from botfront.yml file in workspace dir, created earlier)
8. run "meteor npm run start:docker-compose.dev"
9. open localhost with port specified in package.json ( 'start:docker-compose.dev' )
10. Complete the set up
11. Add some data and train
12. Training gets failed

**Expected Result**
Training of bot should succeed

**Screenshots**
![Screenshot from 2020-05-29 04-12-04](https://user-images.githubusercontent.com/51059452/83201422-0ec75480-a163-11ea-8cef-9bd46b4b9134.png)

**Desktop**
 - OS: Ubuntu
 - Browser Chrome
 - Botfront 0.23.0

Note: Working fine if project started by "botfront up" instead of "botfront up -e botfront"

**Comment by pheel** [comment]
The docs don't say it, but .botfront/botfront.yml needs to be updated for the BF_URL variable. If you're running Docker for Mac or Windows, it should be `http://host.docker.internal:3000/graphql`. See https://github.com/botfront/botfront/issues/632
