### ISSUE TITLE
rasa fails to start because it cannot get the service configuration

### ISSUE THREAD

**Issue by vasconce1o** [botfront/botfront#631]
I am trying to run botfront 0.24.3 from a fresh install, but rasa fails to start because:
rasa.utils.botfront  - Trying to fetch config from http://botfront:3000/graphql (retry #8)
This is docker-compose ps for Ubuntu 18.04

![image](https://user-images.githubusercontent.com/23300404/84443953-a53d5080-ac0e-11ea-8ea3-acd19126ce46.png)

**Comment by pheel** [comment]
@vasconce1o It will do that until you set up your botfront project for the first time.

**Comment by vasconce1o** [comment]
That was the problem.
Thank you.

**Comment by Vonisoa** [comment]
Can you explain more what to do please? I'm having the same issue
