### ISSUE TITLE
Can't run botfront in development mode

### ISSUE THREAD

**Issue by Johnny-AM** [botfront/botfront#642]
I followed every single step, one by one. the last step, when running the meteor command, displayed the following errors. Help please..
![Screenshot (117)](https://user-images.githubusercontent.com/67067569/85204028-51bbb880-b31a-11ea-8310-daa7dff817d4.png)

**Comment by pheel** [comment]
Duplicate of [this](https://spectrum.chat/botfront/general/cant-run-botfront-in-development-mode~5515b4b0-98a2-42da-a3b6-878b5c4f5de2).
