### ISSUE TITLE
The system cannot find the file specified.

### ISSUE THREAD

**Issue by jehanzaib12** [botfront/botfront#651]
I have changed cp with copy to install botfront in windows but when i does it, it says:

> botfront@0.25.0-rc.1 postinstall C:\botfront\botfront
> copy -R /node_modules/semantic-ui-css/themes/default/assets/fonts ./public/ && copy -R /node_modules/semantic-ui-css/themes/default/assets/fonts ./client/

The system cannot find the file specified.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! botfront@0.25.0-rc.1 postinstall: `copy -R /node_modules/semantic-ui-css/themes/default/assets/fonts ./public/ && copy -R /node_modules/semantic-ui-css/themes/default/assets/fonts ./client/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the botfront@0.25.0-rc.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kkc\AppData\Roaming\npm-cache\_logs\2020-06-29T07_28_26_822Z-debug.log

--- I am running it in windows powershell

**Comment by pheel** [comment]
https://superuser.com/questions/206036/commmand-line-command-to-copy-entire-directory-including-directory-folder-to-a

**Comment by pheel** [comment]
Closing for now. Reopen if you think it's needed.
