### ISSUE TITLE
Form option not available

### ISSUE THREAD

**Issue by ROCKMOHAN** [botfront/botfront#654]
While i can create a story in botfront. I have not any such options to create a form and handle slots.

the doc here - https://botfront.io/docs/rasa/forms-slot-filling/ 
is suggesting it is available only on cloud or enterprise version.

Can we implement it here or is it already available.

**Comment by znat** [comment]
Hi @ROCKMOHAN, at the moment forms are are a premium features and are only available in cloud and enterprise version
