### ISSUE TITLE
Start Evaluation Internal Server Error

### ISSUE THREAD

**Issue by oguzhankarahan** [botfront/botfront#659]
**Describe the bug**
I added the training data and completed the training. I got the first evaluation result. I added training data and trained again. But when I want to get an evaluation result, it shows "Internal Server Error". I deleted all training data and uploaded it again. It gave the same error again. I get the same error in both local and azure server.

Botfront Version : 25.1

**To Reproduce**
1. Go to 'NLU / Evaluation'
2. Click on 'Start Evaluation'
3. See error
**Screenshots**
<img width="1689" alt="Ekran Resmi 2020-07-08 13 35 51" src="https://user-images.githubusercontent.com/11270584/86909548-e72fb880-c120-11ea-8c52-8155e084e4d0.png">

**Comment by znat** [comment]
Hi @oguzhankarahan , do you see anything in the logs (`botfront logs`)?

**Comment by oguzhankarahan** [comment]
Hi, logs look like the following.

botfront-rasa   | [2020-07-08 10:35:29 +0000] [1] [ERROR] Exception occurred while handling uri: 'http://rasa:5005/model/test/intents?language=tr'
botfront-rasa   | Traceback (most recent call last):
botfront-rasa   |   File "/opt/venv/lib/python3.7/site-packages/sanic/app.py", line 976, in handle_request
botfront-rasa   |     response = await response
botfront-rasa   |   File "/opt/venv/lib/python3.7/site-packages/rasa/server.py", line 181, in decorated
botfront-rasa   |     result = await result
botfront-rasa   |   File "/opt/venv/lib/python3.7/site-packages/rasa/server.py", line 932, in evaluate_intents
botfront-rasa   |     _, nlu_model = model.get_model_subdirectories(model_directory)
botfront-rasa   |   File "/opt/venv/lib/python3.7/site-packages/rasa/model.py", line 233, in get_model_subdirectories
botfront-rasa   |     unpacked_model_path
botfront-rasa   | rasa.exceptions.ModelNotFound: No NLU or Core data for unpacked model at: '/tmp'.
botfront-app    | 2020-07-08T10:35:29.097Z [error] : POST at http://rasa:5005/model/test/intents?language=tr failed at response time user: PSnwoRrp43uumvBzr /imports/api/instances/instances.methods.js - rasa.evaluate.nlu with {"modelId":"Z5RPru6PkMsXpj2tk","projectId":"bf","testData":null} url: http://rasa:5005/model/test/intents?language=tr  data: "Too much data." error: Error: Request failed with status code 500


How can I fix this?

**Comment by pheel** [comment]
@oguzhankarahan Thanks for the bug report. Looking into it.

**Comment by pheel** [comment]
Fixed in https://github.com/botfront/rasa-for-botfront/commit/ce50ad766cee184ea0b43fb9c9ef1a82dbf09b6e, coming on next patch release.

**Comment by oguzhankarahan** [comment]
Thanks, train bug fixed :) but evaluation error continues.
