### ISSUE TITLE
after install and create account. Then webpage show error.

### ISSUE THREAD

**Issue by yckiong** [botfront/botfront#662]
**Describe the bug**
Here is the report:

```
Version: 0.25.1
Path: /project/bf/stories
Trace: TypeError: NetworkError when attempting to fetch resource.
    in 
    in Unknown
    in Suspense
    in c
    in Unknown
    in div
    in Unknown
    in div
    in t
    in div
    in t
    in div
    in div
    in W
    in t
    in Connect(t)
    in c
    in Unknown
    in RouterContext
    in Router
    in o
    in c
    in t
    in DocumentTitle
    in SideEffect(DocumentTitle)
```

**To Reproduce**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by znat** [comment]
Are you running Botfront on your local machine or a remote server? See here: https://botfront.io/docs/deployment/configuration/

**Comment by yckiong** [comment]
remote server, after changing to public ip. now fixed. thanks
