### ISSUE TITLE
Error on starting botfront

### ISSUE THREAD

**Issue by gotorishab** [botfront/botfront#673]
**Describe the bug**
Here is the report:

```
Version: 0.25.4
Path: /project/bf/stories
Trace: TypeError: Failed to fetch
    in TypeError: Failed to fetch
    in Unknown
    in Suspense
    in c
    in Unknown
    in div
    in Unknown
    in div
    in t
    in div
    in t
    in div
    in div
    in W
    in t
    in Connect(t)
    in c
    in Unknown
    in RouterContext
    in Router
    in o
    in c
    in t
    in DocumentTitle
    in SideEffect(DocumentTitle)
    in U
```

**To Reproduce**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by znat** [comment]
Hi @gotorishab was it on your local machine or on a remote server?
Generally it is because env vars are not set properly: https://botfront.io/docs/installation/server-cluster/#environment-variables

**Comment by gotorishab** [comment]
> Hi @gotorishab was it on your local machine or on a remote server?
> Generally it is because env vars are not set properly: https://botfront.io/docs/installation/server-cluster/#environment-variables

**Comment by gotorishab** [comment]
> Hi @gotorishab was it on your local machine or on a remote server?
> Generally it is because env vars are not set properly: https://botfront.io/docs/installation/server-cluster/#environment-variables



This link works. Thanks
