### ISSUE TITLE
Entity disappear in the evaluation and  playground

### ISSUE THREAD

**Issue by engahmed1190** [botfront/botfront#682]
**Describe the bug**
suddenly entity labeling is not working in the evaluation panel  and playground .although it works correctly in the API section  

**To Reproduce**
1. Go to 'NLU'
2. Click on 'Evaluation'
3. Scroll down to 'Report'

**Expected behavior**
The entity report should provide the predicted labeling for entities. 

**Screenshots**
![image](https://user-images.githubusercontent.com/25582838/88171340-73f96c80-cc1f-11ea-9683-8c9ad10ca3f9.png)
![image](https://user-images.githubusercontent.com/25582838/88171374-7fe52e80-cc1f-11ea-877f-2ab4409b6ae5.png)
![image](https://user-images.githubusercontent.com/25582838/88171512-bae76200-cc1f-11ea-8bed-b1ab4c37b6f5.png)
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Botfront Version : 25.3
Rasa for Botfront Version: 1.10.3-bf.2

**Comment by znat** [comment]
@GuillaumeTech can add a fix for this in #692 ?

**Comment by engahmed1190** [comment]
Hello @znat . Any time frame for this bug . Thanks in advance

**Comment by MatthieuJnon** [comment]
We can't commit to a precise date right now, but it's being addressed. We will let you know as soon as it's done
