### ISSUE TITLE
Hard coded action url

### ISSUE THREAD

**Issue by znat** [botfront/botfront#70]
Why exactly do we have a hard coded value here? Should be taken from endpoints and not env
https://github.com/botfront/botfront/blob/faee3d91ac56df7e2046f1b4f95ba80bdc6ab274/botfront/imports/api/endpoints/endpoints.docker-compose.js#L11

**Comment by pheel** [comment]
This is the hard-coded default to _populate_ endpoints.

**Comment by znat** [comment]
And it IS in the endpoints and should be taken from there

**Comment by znat** [comment]
@pheel, can this one be closed?

**Comment by znat** [comment]
@pheel??

**Comment by znat** [comment]
@pheel??
