### ISSUE TITLE
Missing "Form" menu item under the "+" button inside Stories tab

### ISSUE THREAD

**Issue by predoctech** [botfront/botfront#713]
**Describe the bug**
Am on latest v0.25.9 and looking to set up Forms through the Add "+" button under "Stories" tab.  However there is no "Form" menuitem to choose from, and all the "+" button can add are story groups.

**To Reproduce**
1. Go to 'Stories' tab
2. Click on '+' button
3. No menu item for "Form" appears

**Expected behavior**
An item to add Form after clicking the "+" button.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Ubuntu 18.04]
 - Browser [chrome]
 - Version [0.25.9]

**Additional context**
Is the "Form" interface in Botfront dependent on some other setup in the frontend?

**Comment by MatthieuJnon** [comment]
Hi, as you can see on the documentation at the top of [this page](https://botfront.io/docs/rasa/forms-slot-filling/#slot-filling-and-forms) the forms feature is only available for Botfront Cloud and Botfront Enterprise.
Though, we have plans to bring some of that feature to this open source version. It should be in Botfront 0.27 probably. I'll let you know once it's out.

**Comment by shreeraj04** [comment]
Is there any plans for the forms in open source ? I am running botfront 0.27 but still I don't see Forms option.
