### ISSUE TITLE
Rest API.

### ISSUE THREAD

**Issue by juliolitwin** [botfront/botfront#716]
Yo,

How I can to enable the /webhooks/rest/webhook/ in the botfront? My goal is just to use the botfront like only UI to managment my RASA.

Thanks.

**Comment by znat** [comment]
Hi @juliolitwin you mean the Rasa rest channel?

**Comment by juliolitwin** [comment]
Hello @znat,

Yeah, where I can send the sender and the message, and receive the response.

Cheers.

**Comment by pheel** [comment]
Closing this. Reopen as needed.
