### ISSUE TITLE
Botfront not stable after installation

### ISSUE THREAD

**Issue by joshypallan** [botfront/botfront#720]
My name is Joshy Pallan, From India. Currently working in Kuwait. IT Engineer.
First Of All, thanks a lot for you and your team, to make BotFront as an OpenSource Project.

I am working for an Non Profitable Organization, in INDIA,   as requested by the organization, i am in the process of implementing a simple ChatBot,
And i choose BotFront On Premise Product.
i have installed BotFront in a  VM.  Installation went smoothly.  and i have created a simple Chatbot flow using the Web GUI.  it was working fine.  And after 2 days , when i try to login as a admin, it is asking for creating new user.  my previous created setup all vanished...

Could you please help me on this issue.

we are not in a position to go with paid solution.

Thanks in Advance,

Joshy

**Comment by znat** [comment]
Hi @joshypallan this is probably related to the volume for MongoDB not set correctly. The data is not persisted outside the container and disappears when the container is restarted. Make sure that the paths in the docker-compose file exist

**Comment by joshypallan** [comment]
Dear Nathan,

Thanks for you response,
here below is the content of docker-compose.yml 

----------------------
######################################################################################################
# This file is generated when `botfront up` is invoked.                                              #
# Changes in .botfront/botfront.yml and .botfront/docker-compose-template.yml will be reflected here #
######################################################################################################

version: '3.0'
services:
  botfront:
    image: 'botfront/botfront:v0.25.9'
    container_name: botfront-app
    restart: always
    networks:
      - botfront-network
    volumes:
      - './models/:/app/models'
    ports:
      - '8888:3000'
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      PORT: 3000
  botfront-api:
    image: 'botfront/botfront-api:v0.25.9'
    container_name: botfront-api
    networks:
      - botfront-network
    restart: always
    depends_on:
      - mongo
    ports:
      - '8080:8080'
    env_file:
      - .env
  rasa:
    build:
      context: ./rasa
      args:
        RASA_IMAGE: '${IMAGES_CURRENT_RASA}'
    container_name: botfront-rasa
    networks:
      - botfront-network
    restart: always
    ports:
      - '5005:5005'
    volumes:
      - './models/:/app/models'
    env_file:
      - .env
  actions:
    build:
      context: ./actions
      args:
        RASA_SDK_IMAGE: '${IMAGES_CURRENT_ACTIONS}'
    container_name: botfront-actions
    networks:
      - botfront-network
    restart: always
    ports:
      - '5055:5055'
    volumes:
      - './actions:/app/actions'
    command:
      - start
      - '--debug'
      - '--actions'
      - actions
    env_file:
      - .env
  duckling:
    image: 'botfront/duckling:latest'
    container_name: botfront-duckling
    networks:
      - botfront-network
    restart: always
    ports:
      - '8000:8000'
  mongo:
    image: 'mongo:latest'
    container_name: botfront-mongo
    restart: always
    networks:
      - botfront-network
    volumes:
      - './botfront-db:/data/db'
    ports:
      - '27017:27017'
    env_file:
      - .env
networks:
  botfront-network: {}
volumes:
  botfront-db: null
----------------------

Could you please verify, i am new to BotFront Chatbot.

Thanks in Advance,
Joshy Jose Pallan

**Comment by sarvajeethaldar** [comment]
> The folders botfront-db and models must exist, be accessible, and the user running botfront must have write permissions in them

Did all of  this but still my data is disappearing. Please help
