### ISSUE TITLE
Unable to login / reload to botfront 

### ISSUE THREAD

**Issue by meadovian** [botfront/botfront#734]
**Describe the bug**
Here is the report:

```
Version: 0.25.8-ee.1
Path: /project/ejTvC54CmXGkP7ukG/stories
Trace: Error: Could not access u7j98LaWbwyNv9tMi,0nTAu7cRc
    in <
    in q
    in Connect(q)
    in c
    in h
    in ForwardRef
    in ForwardRef
    in Connect(Component)
    in div
    in h
    in div
    in t
    in div
    in t
    in c
    in Q
    in ForwardRef
    in ForwardRef
    in withRouter(Component)
    in Connect(withRouter(Component))
    in Suspense
    in c
    in Unknown
    in div
    in Unknown
    in div
    in t
    in div
    in t
    in div
    in div
    in V
    in ForwardRef
    in ForwardRef
    in Connect(Component)
    in c
    in Unknown
    in RouterContext
    in Router
    in o
    in c
    in t
    in DocumentTitle
    in SideEffect(DocumentTitle)
    in ee
```

**To Reproduce**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MatthieuJnon** [comment]
Can you try opening the developer console (F12), typing `localstorage.clear()` press enter and then try to reload the website ?

**Comment by meadovian** [comment]
I'm sure that would have worked: I logged back in at the top level, thanks for being speedy!

**Comment by MatthieuJnon** [comment]
Sorry I'm a bit confused by your answer, is your issue solved or not ?
No problem

**Comment by meadovian** [comment]
Yes, resolved, thank you.

**Comment by MatthieuJnon** [comment]
Great! Did you do anything in particular before landing on this issue though ?

**Comment by meadovian** [comment]
It appears I may have but I'd not be able to tell you; at about this same time training errors arrived. 
Investigating / debugging now and I'll report back if I have anything of value for you.  
NRN
