### ISSUE TITLE
unable to tag entities in no-whitespace language

### ISSUE THREAD

**Issue by ningchaoar** [botfront/botfront#746]
**Describe the bug**
Unable to tag entities in no-whitespace language (e.g. chinese or japanese).
Entity edition window only appers when the whole sentence is selected, however, unlike english, words in chinese are not splited by whitespace, so entities is a sub string of sentence. It seems that botfront only recognize words that is surrounded by whitesapce.
Change project language to chinese and using JiebaTokenizer in nlu pipeline doesn't help.

**To Reproduce**
1. Go to 'NLU'-'Examples'
2. tag entites for a non-english sentence
3. select words, not the whole sentence

**Expected behavior**
Entity edition window should appear when sub-string of a sentence is selected

**Screenshots**
![GIF 20-9-11 14-55-04](https://user-images.githubusercontent.com/39253972/92879952-1c69c700-f440-11ea-92fb-d0f11c0c6a0e.gif)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04.
 - Browser: Chrome 81.0.4044.92
 - Version: 0.26.0
 - Run botfront in development mode.

**Comment by ningchaoar** [comment]
> Hi @ningchaoar , thanks for reporting.
> Do you know if Rasa supports entities in no-whitespace languages?

Hi, as far as I know, Rasa has two ways to deal with no-whitespace languages:
1. use tokenizer(JiebaTokenizer for chinese) to do word segmentation, then use bulid-in entity extractor like CRFEntityExtractor or DIETClassifier
or 2. use char-level NER model as a custom component.

**Comment by pheel** [comment]
Hi @ningchaoar,
You're right. The tagging UI right now depends on spaces to help find natural words. We'll add a no-whitespace language mode in the future. 🙏

**Comment by ningchaoar** [comment]
@pheel That would be good news to multi-language users, thanks for developing such great platform.

**Comment by yingkai1181** [comment]
@pheel good to hear^^, any news on this? Thanks~

**Comment by pheel** [comment]
@yingkai1181 Someone is working on a PR right now!

**Comment by yingkai1181** [comment]
@pheel nice, our company is really looking forward to this feature~ thx

**Comment by pheel** [comment]
As you may know, this feature is out!
