### ISSUE TITLE
Version Control

### ISSUE THREAD

**Issue by kearnsw** [botfront/botfront#753]
**Is your feature request related to a problem? Please describe.**
We need to keep multiple versions of the bot for staging/rollback purposes. Also, as we have multiple authors, it is important that they are able to keep their data in sync and stored securely.

**Describe the solution you'd like**
Add version control with git support.

**Describe alternatives you've considered**
Writing scripts to export periodically and upload these to the repository or switching to Rasa X.

**Comment by pheel** [comment]
We realize this is a crucial feature. It is definitely on the roadmap, but we can't commit on a release timeline for the moment.

**Comment by pheel** [comment]
Git integration is in `v1.0.0-rc.3` at the moment!
