### ISSUE TITLE
endpointsFetched' as it is null.

### ISSUE THREAD

**Issue by Joker1212** [botfront/botfront#772]
the log is 

2020-10-02 14:33:25 ERROR    sgqlc.endpoint.http  - GraphQL query failed with 1 errors
botfront-rasa   | 2020-10-02 14:33:25 DEBUG    rasa.utils.botfront  - Cannot destructure property 'endpoints' of 'endpointsFetched' as it is null.

i just login the website but nothing happen so i look up the logs

**Comment by pheel** [comment]
You will usually see this until a project has been initialized.

**Comment by diegodorgam** [comment]
What that means exactly?

**Comment by ptrkdy** [comment]
I resolved this error by running step 7 in the docs:
https://botfront.io/docs/installation/server-cluster#environment-variables

Run `botfront set-project <project_id>`. Rasa will restart and fetch that project’s configuration.

Hope that helps you. Cheers!
