### ISSUE TITLE
"Quick Start" can't login

### ISSUE THREAD

**Issue by wewillydy** [botfront/botfront#777]
**Describe the bug**
Here is the report:

```
Version: 0.27.0
Path: /project/bf/dialogue
Trace: TypeError: Failed to fetch
    in TypeError: Failed to fetch
    in Unknown
    in Suspense
    in d
    in div
    in Unknown
    in div
    in t
    in div
    in t
    in div
    in div
    in B
    in ForwardRef
    in ForwardRef
    in Connect(Component)
    in c
    in Unknown
    in RouterContext
    in Router
    in o
    in c
    in t
    in DocumentTitle
    in SideEffect(DocumentTitle)
    in $
```

**To Reproduce**
1. I use "npm install -g botfront"  setup the botfront on server, It seems all is successful and I get"Botfront is UP! "
2. I visit the botfront via http://serverIp:8888, I register a user then input the user and password to login...
3. Then the page show "Oops!","Something went wrong. Sorry about that."
**Desktop (please complete the following information):**
 - OS: [e.g. iOS] linuxcent OS 6.5
 - Browser [e.g. chrome, safari] chrome

**Additional context**

**Comment by wewillydy** [comment]
I use "botfront logs", get some logs as below:
botfront-rasa   | 2020-10-12 08:02:13 INFO     root  - Starting Rasa server on http://localhost:5005
botfront-rasa   | 2020-10-12 08:02:13 DEBUG    rasa.core.utils  - Using the default number of Sanic workers (1).
botfront-rasa   | 2020-10-12 08:02:13 INFO     root  - Enabling coroutine debugging. Loop id 93967475153024.
botfront-rasa   | 2020-10-12 08:02:13 DEBUG    root  - Could not load interpreter from 'models'.
botfront-rasa   | 2020-10-12 08:02:13 DEBUG    rasa_addons.core.tracker_stores.botfront  - BotfrontTrackerStore tracker store created
botfront-rasa   | 2020-10-12 08:02:13 DEBUG    rasa.core.tracker_store  - Connected to BotfrontTrackerStore.
botfront-rasa   | 2020-10-12 08:02:13 DEBUG    rasa.core.lock_store  - Connected to lock store 'InMemoryLockStore'.
**botfront-rasa   | /opt/venv/lib/python3.7/site-packages/rasa/utils/common.py:363: UserWarning: Could not load local model in 'models'.**
botfront-rasa   | 2020-10-12 08:02:13 DEBUG    rasa.core.nlg.generator  - Instantiated NLG to 'TemplatedNaturalLanguageGenerator'.
botfront-rasa   | 2020-10-12 08:02:13 INFO     root  - Rasa server is up and running.

botfront-mongo  | {"t":{"$date":"2020-10-12T08:37:29.128+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn14","msg":"Connection ended","attr":{"remote":"172.22.0.6:41610","connectionId":14,"connectionCount":7}}

**Comment by znat** [comment]
There are plenty of exact same issue in the repo. You probably did not set ROOT_URL
