### ISSUE TITLE
Error after botfront login

### ISSUE THREAD

**Issue by skyridertk** [botfront/botfront#781]
**Describe the bug**
Here is the report:

```
Version: 0.27.0
Path: /project/bf/dialogue
Trace: TypeError: Failed to fetch
    in TypeError: Failed to fetch
    in Unknown
    in Suspense
    in d
    in div
    in Unknown
    in div
    in t
    in div
    in t
    in div
    in div
    in B
    in ForwardRef
    in ForwardRef
    in Connect(Component)
    in c
    in Unknown
    in RouterContext
    in Router
    in o
    in c
    in t
    in DocumentTitle
    in SideEffect(DocumentTitle)
    in $
```

**To Reproduce**
1. npm install -g botfront
2. mkdir mybot
2. cd mybot && botfront init
3. botfront up
4. Go to http://localhost:8888
5. Enter log in details and sign in
6. See error

**Desktop (please complete the following information):**
 - OS: Ubuntu 20
 - Browser : Chrome
 - Version: 86.0.4240.75 (Official Build) (64-bit)

**Comment by skyridertk** [comment]
If I quickly click other menu options, it doesn't crash. Thus it seems there is something broken in the dialogue option

**Comment by znat** [comment]
Check the docs to set ROOT_URL

Le mer. 14 oct. 2020 05 h 11, Ian Kahwai <notifications@github.com> a
écrit :

**Comment by skyridertk** [comment]
That worked @znat
