### ISSUE TITLE
'botfront up' starts but never finishes

### ISSUE THREAD

**Issue by digitalWestie** [botfront/botfront#782]
**Describe the bug**
Running botfront up seems to freeze (or is perhaps taking a very very long time).

**To Reproduce**

1. Installed cli with npm 
2. Run `botfront init`
3. Run `botfront up --verbose`

This starts off the process, downloading images etc. but seems to get stuck after pulling `botfront/rasa-for-botfront`.

```
⠦ Starting Botfront...Creating network "botfront-test_botfront-network" with the default driver
⠧ Starting Botfront...Creating volume "botfront-test_botfront-db" with default driver
⠇ Starting Botfront...Building rasa
⠏ Starting Botfront...Step 1/7 : ARG RASA_IMAGE
Step 2/7 : FROM ${RASA_IMAGE}
⠇ Starting Botfront...v1.10.10-bf.3: Pulling from botfront/rasa-for-botfront
⠏ Starting Botfront...
```

**Expected behavior**
I expect this process to take less time, or if it is a long process, provide more indication of progress.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.5 LTS
 - 

**Additional context**
Docker is version 19.03.6, build 369ce74a3c.

I can see various docker images have been pulled in the process e.g. 

botfront/botfront                        v0.27.0             765fbf38e667        9 days ago          593MB
botfront/botfront-api                    v0.27.0             575c689bf333        9 days ago          253MB
botfront/duckling                        latest              257be8a3f16c        4 months ago        120MB

**Comment by znat** [comment]
Starting Rasa actually implies downloading the rasa-for-botfront image, which is not clear from the CLI output: Botfront builds an image FROM botfront/rasa-for-botfront.
So it's normal that starting for the 1st times takes longer.
How long did you wait?

**Comment by digitalWestie** [comment]
Hey, I left it going for a while. It's been about an hour since that last message. Got there in the end though! 

        🎉 🎈  Botfront is UP! 🎉 🎈

Just need to be more patient :+1:
