### ISSUE TITLE
Dialogue oops error

### ISSUE THREAD

**Issue by overflood** [botfront/botfront#791]
**Describe the bug**
I've completed the setup and landed into this error

```
Version: 0.27.1
Path: /project/bf/dialogue
Info:
TypeError: Failed to fetch
    in TypeError: Failed to fetch
    in Unknown
    in Suspense
    in d
    in div
    in Unknown
    in div
    in t
    in div
    in t
    in div
    in div
    in $
    in ForwardRef
    in ForwardRef
    in Connect(Component)
    in c
    in Unknown
    in RouterContext
    in Router
    in o
    in c
    in t
    in DocumentTitle
    in SideEffect(DocumentTitle)
    in $
```

**To Reproduce**

**Desktop (please complete the following information):**
 - Browser: Brave

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pheel** [comment]
https://github.com/botfront/botfront/issues/790
https://github.com/botfront/botfront/issues/789
