### ISSUE TITLE
Support for RASA 2.0

### ISSUE THREAD

**Issue by shreeraj04** [botfront/botfront#807]
The current Botfront is not supported for Rasa 2.0 I believe since I am getting error during importing stories. When can we expect the support for RASA 2.0 ?

**Comment by pheel** [comment]
Hey @shreeraj04. Support for Rasa 2 is announced for Botfront 1.0.0. Alpha is out, if you want to check it out:

https://github.com/botfront/botfront/releases/tag/v1.0.0-alpha.1
https://www.npmjs.com/package/botfront/v/1.0.0-alpha.1

It doesn't support importing yet.

Release shouldn't take much longer!

**Comment by shreeraj04** [comment]
Thank you @pheel I will try it out.

**Comment by shreeraj04** [comment]
When can we expect the official release ? @pheel

**Comment by stephanrb3** [comment]
The new release with 2.0 support will support importing .yml files right?

**Comment by shreeraj04** [comment]
@pheel I alpha versions doesn't work as expected. The training itself is not happening. Not very sure where is the problem. Getting error "training_data.json" does not exist, then the PUT call to load the model fails. But the model is saved into the models folder.

**Comment by pheel** [comment]
`v1.0.0-rc.3` is out, with `v1.0.0` coming out any moment.
