### ISSUE TITLE
Training & Loading the model is failing

### ISSUE THREAD

**Issue by shreeraj04** [botfront/botfront#826]
Botfront training the model is failing

1. I did botfront init
2. Opened the app in the browser
3. Added few data for greeting and good bye
4. Clicked on train button
5. Got the below error in logs and UI

![image](https://user-images.githubusercontent.com/15680777/99220167-22936f80-2804-11eb-81a5-ff38968ef4fb.png)

![image](https://user-images.githubusercontent.com/15680777/99220187-2de69b00-2804-11eb-96fa-565569f1c00b.png)

Expected behavior is to be trained without error.

 - OS: Windows 10
 - Browser Opera
 - Version Botfront v1.0.0-alpha.1 , 1.0.0-alpha.2 & 1.0.0-alpha.3

Is there anything which I am doing wrong ?
Can you help in understanding how to add rules//forms in this new version ?

**Comment by pheel** [comment]
Thanks. This is a known issue. The easy fix to get started (if you're not using Gazette), is to remove the `- name: rasa_addons.nlu.components.gazette.Gazette` line from NLU > Settings > Pipeline.

**Comment by shreeraj04** [comment]
Thanks @pheel . I saw a new feature in latest version i.e forms/rules. May I know how to use these in botfront ui ?  Also activating loop and deactivate loop as well. Thanks in advance.

**Comment by shreeraj04** [comment]
Not sure whether I am configuring correctly or now. I am getting the below error. Couldn't find any documentation for this.
Pls help..

![image](https://user-images.githubusercontent.com/15680777/99264033-fa2c6500-2845-11eb-9a9f-55402b1b1616.png)

**Comment by pheel** [comment]
Closed as you have started https://github.com/botfront/botfront/issues/828 regarding that.
