### ISSUE TITLE
How to use loops in stories or rules ?

### ISSUE THREAD

**Issue by shreeraj04** [botfront/botfront#828]
There is a new enhancement in RASA 2.0 i.e rules. I saw this in the alpha version of botfront as well. But may I get to know how to use this forms feature in the botfront UI ? I couldn't find any documentation for the same.

Basically we need to declare the forms in the domains and then activate/deactivate in the stories/rules. But here how to do the same ?

I tried with the below, but I am getting the error related to Tensorflow

![image](https://user-images.githubusercontent.com/15680777/99387028-4edce800-28f9-11eb-83b1-85f2287e4912.png)

![image](https://user-images.githubusercontent.com/15680777/99387105-6d42e380-28f9-11eb-90ea-f87369a66cea.png)

 - OS: Windows 10
 - Browser Opera
 - Version botfront alpha.3

Thanks in advance

**Comment by pheel** [comment]
Closing for staleness. Please reopen if you are still having the issue.
