### ISSUE TITLE
How to test stories

### ISSUE THREAD

**Issue by Right-ty** [botfront/botfront#848]
I see the [rasa document](https://legacy-docs-v1.rasa.com/user-guide/testing-your-assistant/) shows support test stories.
I don't know how botfront tests the stories. Does it support this feature？

**Comment by pheel** [comment]
Support for end-to-end story testing in Botfront is coming very, very soon!

**Comment by pheel** [comment]
Enjoy this feature in `v1.0.0-rc.3`, or `v1.0.0` when released.
