### ISSUE TITLE
training fails after some time

### ISSUE THREAD

**Issue by ilushka85** [botfront/botfront#857]
botfront-rasa   | 2021-01-06 18:13:14 ERROR    rasa.model  - Failed to extract model at models/model-bf.tar.gz. Error: Compressed file ended before the end-of-stream marker was reached

Receive this error and cannot train.

**Comment by pheel** [comment]
Run `rm models/model-bf.tar.gz && botfront restart rasa` from your project dir. Then retrain.

**Comment by pheel** [comment]
Feel free to reopen.
