### ISSUE TITLE
How to change the default training time?

### ISSUE THREAD

**Issue by Abu-Ishak** [botfront/botfront#865]
I have about 400 story and 4k examples. I'm using Botfront local version in windows matching. When I train them, it's failing because of time out.
How can I change the default training time?

**Comment by Abu-Ishak** [comment]
@pheel @kenrilea @MatthieuJnon bro, would you please help me out 🥺.

**Comment by MatthieuJnon** [comment]
What version are you using @Abu-Ishak ? On recent versions there should be no timeout and if you want one you should be able to set it using the env variable `TRAINING_TIMEOUT`

**Comment by Abu-Ishak** [comment]
@MatthieuJnon thanks for your reply. I'm using botfront version: 0.26.0 . Does the timeout parameter use mS? If I want to increase my training time to 60 min, then how can I write it?

**Comment by pheel** [comment]
@Abu-Ishak, if you upgrade to >=0.27.0, you will get no timeout by default. Current is 0.27.5.
