### ISSUE TITLE
Create a form

### ISSUE THREAD

**Issue by DrMartiner** [botfront/botfront#867]
**Describe the bug**
I can't create a form via UI. How can I create a form?

**To Reproduce**
1. Added `FormPolicy` 
2. Clicked to "plus" button

**Expected behavior**
Form to creating form

**Screenshots**
<img width="360" alt="Снимок экрана 2021-01-18 в 22 25 45" src="https://user-images.githubusercontent.com/730717/104960293-999fdc80-59dc-11eb-9fc7-ffc8db77cdf2.png">

**Comment by pheel** [comment]
Botfront forms are currently an Enterprise feature, unfortunately. You can still add forms in the default domain.
