### ISSUE TITLE
How can I buy an Enterprise?

### ISSUE THREAD

**Issue by DrMartiner** [botfront/botfront#870]
How can I buy an Enterprise version?

**Comment by pheel** [comment]
Enterprise is getting discontinued. There is a _chance_ it will be open-sourced in the future.

**Comment by xiaoxiper** [comment]
Is there a way to try the enterprise version first？

**Comment by xiaoxiper** [comment]
and what about the cloud version?

**Comment by xiaoxiper** [comment]
> Enterprise is getting discontinued. There is a _chance_ it will be open-sourced in the future.

Is there a way to try the enterprise version now？

**Comment by MatthieuJnon** [comment]
We're officially releasing the enteprise version in open source, track the PR @pheel mentionned if you want updates, it should take a few weeks.
The cloud version is discontinued, we will have documentation on how to host the enteprise version yourself on your infra

**Comment by xiaoxiper** [comment]
Thanks
