### ISSUE TITLE
Build from Source 

### ISSUE THREAD

**Issue by engahmed1190** [botfront/botfront#90]
**Is your feature request related to a problem? Please describe.**
I would like to build code from the source 

`npm install -g botfront`

How I can rebuild code again locally. I have used `docker-compose up`

but stopped at  Connecting to MongoDB...
![image](https://user-images.githubusercontent.com/25582838/60434318-2c183980-9c07-11e9-96b7-62a83046cff8.png)

**Comment by znat** [comment]
The Botfront CLI wraps docker-compose
 So you can do `botfront init` to create a new project and `botfront up` to start.
Just typing `botfront` should give you contextual options

**Comment by engahmed1190** [comment]
I want to change some code blocks and then rebuild again. How I can do that

**Comment by engahmed1190** [comment]
OK. Got it `https://github.com/botfront/botfront/tree/master/botfront/docs/guide/developers`

**Comment by znat** [comment]
Just published it: https://spectrum.chat/botfront/general/how-to-build-from-source~2f67146f-7677-495b-ae87-7fdb0caa9b98
