### ISSUE TITLE
session_config in default domain

### ISSUE THREAD

**Issue by alebeta90** [botfront/botfront#903]
Hi friends,

I had been trying to configure session_config in my Default Domain in Settings, but it seems not being taking effect.

Is there a different way to implement it when it comes to Botfront?

am using rasa for botfront 1.9.0-bf.9

It would be good to be able to add session_config to the default domain section
```
session_config:
  session_expiration_time: 0
  carry_over_slots_to_new_session: true
```

thanks in advance

**Comment by dabonde** [comment]
I'm also having this problem.

**Comment by dabonde** [comment]
It made sense that the default domain gets extracted and written during training of the model. I had a look around the botfront codebase at what happens during training. 

The function [extractDomain](https://github.com/botfront/botfront/blob/master/botfront/imports/lib/story.utils.js#L151) in story.utils.js appears to be returning the values from the defaultDomain to be passed over to the rasa instance. 

```
const initialDomain = {
        actions: new Set([...(defaultDomain.actions || []), ...Object.keys(responses)]),
        intents: new Set(defaultDomain.intents || []),  
        entities: new Set(defaultDomain.entities || []),  
        responses: { ...(defaultDomain.responses || {}), ...responses },
        slots: { ...(defaultDomain.slots || {}), ...getSlotsInRasaFormat(slots) },
        forms: {
            ...(defaultDomain.forms || {}),
            ...formGroupIdsToGroupNames(bfForms).reduce(
                (acc, { name, ...rest }) => ({ ...acc, [name]: { ...rest, name } }),
                {},
            ),
        },
    };
```
Looks to be only fetching specific falues rfom the default domain. Session config gets overlooked.

**Comment by alebeta90** [comment]
Hi @dabonde ,

Now it is clear why it is not using the session_config key in the domain.

@znat any chance it could be implemented?

thanks in advance

**Comment by dabonde** [comment]
I've created a pull request #908 with this feature. Seems be working for me locally. I had to adjust a few test cases to include the session_config in the domain. 
It looks like the branch is failing in the automated integration test but the failing tests look unrelated to this? Unsure...
