### ISSUE TITLE
"contact" and "try our demo" links dead on landing page

### ISSUE THREAD

**Issue by WeberJulian** [botfront/botfront#907]
Hi, I'm not sure it's the right place for this but I wanted to talk to Botfront's team about an enterprise licence but both the "contact" and "try our demo" links are dead on [landing page](https://botfront.io/rasa/). Nothing happen when I click on both buttons.

**Comment by MatthieuJnon** [comment]
Hi, the website has just been updated. You don't need an enterprise licence anymore, everything has just been made open source
