### ISSUE TITLE
RASA Instance not reachable

### ISSUE THREAD

**Issue by diegodorgam** [botfront/botfront#909]
I'm trying to install botfront 1.0.0 in a server (VM) using botfront cli, following the exact instructions in this page https://botfront.io/docs/installation/server-cluster, Single Server session of course.
So I ran:
`botfront init`

changed the `root_url` of `.botfront/botfront.yml` to my server's ip address, like this `root_url: 'http://119.9.229.65:8888'`

`cd myproject && botfront up`

Went through registration wizard, and changed default endpoint settings to match the docker-compose URLs, as demonstrated in the tutorial page.

Created a new Project and updated the instance url to `http://rasa:5005`.
So I have these settings in the new project:
Docker services up and running:
![Captura de Tela 2021-02-17 às 11 16 03](https://user-images.githubusercontent.com/12052193/108216794-a3b71700-7111-11eb-87f6-d3d18531d8aa.png)
Endpoints:
<img width="1090" alt="Captura de Tela 2021-02-17 às 11 13 44" src="https://user-images.githubusercontent.com/12052193/108216891-b9c4d780-7111-11eb-80bd-f2766060ea61.png">
Instance:
<img width="604" alt="Captura de Tela 2021-02-17 às 11 13 21" src="https://user-images.githubusercontent.com/12052193/108216952-c9dcb700-7111-11eb-8d48-213b4f492832.png">

Still, my dialogue screen gives me a *disabled Train* button, with a tooltip saying that `Rasa instance not reachable`:
<img width="262" alt="Captura de Tela 2021-02-17 às 11 12 25" src="https://user-images.githubusercontent.com/12052193/108217117-fee90980-7111-11eb-9a2d-41984a6f192c.png">

When I check the of the containers, everything looks fine but the Rasa container which keeps shouting this same log over and over:
```
DEBUG    rasa.utils.botfront  - Cannot destructure property 'endpoints' of 'endpointsFetched' as it is null.
DEBUG    rasa.utils.botfront  - Trying to fetch config from http://botfront:3000/graphql (retry #3196)
ERROR    sgqlc.endpoint.http  - GraphQL query failed with 1 errors
```

Am I missing something? 
I've tried restarting services after new configuration is applied, but it still nothing changes.

Any ideas on how to reach Rasa instance in a single server installation?
PS.: this was not happening in v1.0.0-rc3, started in rc4.

Thanks in advance guys!

**Comment by Gerben-T** [comment]
I have the same issue.

There is a warning in the `rasa` container logs:
```
2021-02-17 14:37:58 WARNING  rasa.utils.common  - Failed to write global config. Error: [Errno 13] Permission denied: '/.config'. Skipping.
```

Not sure if this causes the "fetch config" loop..

**Comment by Gerben-T** [comment]
Possible duplicate of #631

**Comment by diegodorgam** [comment]
there are a few posts about that config permission here `https://forum.rasa.com/t/rasa-x-0-33-docker-compose-rasa-production-1-permission-denied/36350/6`

**Comment by diegodorgam** [comment]
Just tried to remove the `USER 1001` from `rasa/Dockerfile` and builded the image over, so rasa can run as root.
The "config" warning has disappeared, but the "fetch config" error continues.

**Comment by MatthieuJnon** [comment]
Hi, have you set `bf_project_id` to the project id from which you want to fetch the endpoints ?

**Comment by MatthieuJnon** [comment]
In .botfront/botfront.yml

**Comment by MatthieuJnon** [comment]
Once you've set it you have to `botfront restart rasa`, we'll update the doc

**Comment by Gerben-T** [comment]
> Hi, have you set `bf_project_id` to the project id from which you want to fetch the endpoints ?

Changing 
```
bf_project_id: bf
```
to
```
bf_project_id: 'chitchat-Jw0-gbXJt'
```

seems to solve the rasa error, but that means you can only have one active project?

**Comment by MatthieuJnon** [comment]
Yes, you can only have one active project per rasa instance (ideally not the chitchat project, it's going to be removed in the near future)
If you want to have several projects, you have to deploy an instance of rasa for botfront for each one.

**Comment by MatthieuJnon** [comment]
rather than manually changing `bf_project_id` you can also do `botfront set-project <project_id> `

**Comment by diegodorgam** [comment]
Awesome @MatthieuJnon,

I've changed the `.botfront/botfront.yml` file and inserted my project id in there as said:
```
env:
  bf_project_id: 'ApPQMCvdGSdWgDvvP'
```

The Train button is active and everything works as a charm.

Thank you so very much for your rapid attention on this!

**Comment by MatthieuJnon** [comment]
https://github.com/botfront/botfront/pull/910

**Comment by WeberJulian** [comment]
Hi,
The set-project command doesn't work for me, I'm running botfront@1.0.2
![image](https://user-images.githubusercontent.com/17219561/109289047-ee2d4780-7825-11eb-8dc9-48dd66afc7da.png)

**Comment by MatthieuJnon** [comment]
Are you sure you're in your project's folder ? do you see `rasa actions models botfront-db docker-compose.yml` when you do `ls` in that folder ?

**Comment by WeberJulian** [comment]
Yes I'm in the right folder
![image](https://user-images.githubusercontent.com/17219561/109482970-eddbb900-7a7e-11eb-8d74-da66323e36b0.png)

**Comment by WeberJulian** [comment]
> If you want to have several projects, you have to deploy an instance of rasa for botfront for each one.
When you do that, what do you put in the field bf_project_id ? Can it take a list of ids ?
