### ISSUE TITLE
Cannot start service Mongo: network not found

### ISSUE THREAD

**Issue by valdu02100** [botfront/botfront#95]
Hello,

I installed a Linux Mint OS on vitualBox machine.
I installed docker, docker-compose, node js without problems.
Execute the command : `sudo npm install -g botfront`
In my folder project, execute `sudo botfront` and `sudo botfront init`

I receive an error from mongo : [IMAGE](https://ibb.co/CQ85qkW)
My log only content 'Attaching to'

Do you have some tips to fix it?

Thanks for helps
Valentin

**Comment by znat** [comment]
Did you install node with nvm (https://docs.botfront.io/setup/#mac-linux)?. It should avoid having to use `sudo`
This error can happen if another project didn't shut down correctly. So I suppose you had another project running or that you upgraded from a previous version?

Anyways. Try this: `botfront killall --remove-containers`

If it doesn't work, restart your docker daemon.

**Comment by valdu02100** [comment]
Node was already install with `sudo apt-get install nodejs`. Did I already do again with nvm ? 
No, it's the first time I was launch botfont. I use your command and try it again. 

Same error with ne log : [IMG](https://ibb.co/1sqvG5S)

I restart the docker service and lauch again. Same error. 
Duging this operation, I losted two time my network. I use a NAT connexion until my host and my vm.

valentin

**Comment by znat** [comment]
A few ideas:
- from your project folder, run `botfront down` (it wraps docker-compose down so it should remove all resources and expected dependencies)
- did you do run `botfront killall --remove-containers`?

**Comment by valdu02100** [comment]
I already try to use `botfront down` and `botfront killall --remove-containers`.

**Comment by znat** [comment]
Ok. did botfront down help?

Otherwise, can you remember exactly all the steps so we can try to repro? 
Can you try creating another project without using `sudo`(not sure if it's related but you shouldn't have to `sudo npm`

**Comment by valdu02100** [comment]
You have my process in my first message. nothing else.
I need to use sudo, I'm in Linux Mint OS and my user don't any privileage.

**Comment by valdu02100** [comment]
I uninstall from dockers all containers, volumes, images, networks. 
I came back on my folder project and execute `botpress init`. 
I started the project, but always same problem with mongo.

**Comment by valdu02100** [comment]
Hi @znat , 
Thank you very much for your help.

I couldn't find a solution with my other VM. 
I decided to create a new virtual machine with ubuntu lxde 18.10. I followed these commands and Botfront starts...

```
📂{USER}
sudo apt update
#docker
sudo apt install apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
sudo apt update
apt-cache policy docker-ce
#docker-ce
sudo apt install docker-ce
sudo systemctl status docker
sudo apt install
#docker-compose 
sudoo apt install docker-compose
#nodejs
sudo apt   install nodejsr
#npm 
sudo apt install npm

#botfront
npm install -g botfront
sudo botfront
cd {PROJECT}
📂{PROJECT}
sudo botfront up
```
Thank you again.
Valentin
ps:  I really like the UI

**Comment by znat** [comment]
Thanks :) So is it working now?

**Comment by valdu02100** [comment]
Hmm... Not really ^^

I'm on the Chitchat project.
I have examples in the NLU section, not in the answer.
I have created a new story "Greetings".
In two scenarios: 

```
# Hi
* chitchat.greet
- utter_hi
```

```
* chitchat.greet
- utter_bye
```
I trained the model. I would like to test it, click on the bubble at the bottom left. The conversation interface is displayed without the answer area.
![Botfront Error](https://zupimages.net/up/19/28/r344.png)
![Botfront Error](https://zupimages.net/up/19/28/rpfp.png)


Valentin

**Comment by znat** [comment]
We have an issue with Firefox. Can you try with Chrome?
@pheel @MattJoannon

Le ven. 12 juill. 2019 16 h 29, valdu02100 <notifications@github.com> a
écrit :

**Comment by valdu02100** [comment]
Yeah @znat 
Indeed with Chrome it works.

Thank you. Thank you.
