### ISSUE TITLE
[suggestion] Allow to set a bot message to an existing utterance with UI

### ISSUE THREAD

**Issue by WeberJulian** [botfront/botfront#969]
**Is your feature request related to a problem? Please describe.**
I want my bot to way the same same for the story greet and the story get started. Right now it's not possible via UI (I think) and you can only to it in YAML mode.

**Describe the solution you'd like**
It would be nice to add a way in the UI to select a previously defined utterance

**Describe alternatives you've considered**
Going in YAML mode to edit the "utter" feild.

**Comment by brandaobrandisborges** [comment]
I agree with this. Also, I cannot create intentions unless I use a story. It would be nice to have a UI to add intents and entities. I have seen in some tutorials using older botfront versions the tab "insert many" or something like that, but it's not displayed in my UI.
