### ISSUE TITLE
Cannot train model: string indices must be integers

### ISSUE THREAD

**Issue by brandaobrandisborges** [botfront/botfront#986]
**Describe the bug**
I get the following message a few seconds after clicking to train my model:  
  
![image](https://user-images.githubusercontent.com/51330067/112361015-b513b600-8cb1-11eb-9cb6-1a9161eeefcc.png)
  
The error doesn't happen on the default chitchat model.  
I exported the project above and trained it directly on rasa, it works. Wich shows me it's not a NLU data problem.  
I have tried with multiple languages.  
  
**To Reproduce**  
1. botfront init
2. botfront up
3. create new project on botfront gui
4. On terminal, run: botfront set-project PROJECT_ID
5. configure root_url on .botfront/botfront.yml
6. botfront down && botfront up
7. create some stories
8. train
9. see error

**Expected behavior**
The model should be trainned and saved.

**Desktop (please complete the following information):**  
I'm running a virtual machine on azure  
NAME="CentOS Linux"  
VERSION="8"  
ID="centos"  
ID_LIKE="rhel fedora"  
VERSION_ID="8"  
PLATFORM_ID="platform:el8"  
  
I have configured all endpoints to point to my correct VM DNS.
  
**Botfront logs**
`botfront-rasa | 2021-03-24 17:49:37 INFO     rasa.nlu.model  - Finished training component.
botfront-rasa | 2021-03-24 17:49:37 INFO     rasa.nlu.model  - Starting to train component Gazette
botfront-rasa | 2021-03-24 17:49:37 ERROR    rasa.server  - Traceback (most recent call last):
botfront-rasa |   File "/opt/venv/lib/python3.7/site-packages/rasa/server.py", line 1023, in train
botfront-rasa |     training_result = await train_async(**training_payload)
botfront-rasa |   File "/opt/venv/lib/python3.7/site-packages/rasa/train.py", line 180, in train_async
botfront-rasa |     finetuning_epoch_fraction=finetuning_epoch_fraction,
botfront-rasa |   File "/opt/venv/lib/python3.7/site-packages/rasa/train.py", line 372, in _train_async_internal
botfront-rasa |     finetuning_epoch_fraction=finetuning_epoch_fraction,
botfront-rasa |   File "/opt/venv/lib/python3.7/site-packages/rasa/train.py", line 416, in _do_training
botfront-rasa |     finetuning_epoch_fraction=finetuning_epoch_fraction,
botfront-rasa |   File "/opt/venv/lib/python3.7/site-packages/rasa/train.py", line 848, in _train_nlu_with_validated_data
botfront-rasa |     **additional_arguments,
botfront-rasa |   File "/opt/venv/lib/python3.7/site-packages/rasa/nlu/train.py", line 116, in train
botfront-rasa |     interpreter = trainer.train(training_data, **kwargs)
botfront-rasa |   File "/opt/venv/lib/python3.7/site-packages/rasa/nlu/model.py", line 209, in train
botfront-rasa |     updates = component.train(working_data, self.config, **context)
botfront-rasa |   File "/opt/venv/lib/python3.7/site-packages/rasa_addons-2.3.3.3-py3.7.egg/rasa_addons/nlu/components/gazette.py", line 68, in train
botfront-rasa |     name = item["value"]
botfront-rasa | TypeError: string indices must be integers
botfront-rasa |
botfront-rasa | 2021-03-24 17:49:37 ERROR    rasa.server  - An unexpected error occurred during training. Error: string indices must be integers
`

**Comment by brandaobrandisborges** [comment]
I have just been able to find a temporary solution: disable the Gazett pipeline.
This is the pipeline I'm currently running:  

pipeline:
  - name: WhitespaceTokenizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 200
\#  - name: rasa_addons.nlu.components.gazette.Gazette
  - name: >-
      rasa_addons.nlu.components.intent_ranking_canonical_example_injector.IntentRankingCanonicalExampleInjector
  - name: EntitySynonymMapper

**Comment by isabirahmed** [comment]
@brandaobrandisborges : Thanks that helped.

**Comment by thomas779** [comment]
I'm getting this issue as OP.  

However, commenting ```# - name: rasa_addons.nlu.components.gazette.Gazette``` works for the time being.

**Comment by sreenathmurali** [comment]
I am getting same error after commenting Gazett pipeline..
![botfront](https://user-images.githubusercontent.com/1404763/113272663-7c02c380-92f9-11eb-95ca-8b5eb61413da.JPG)

**Comment by a7u7a** [comment]
Hi! I also commented out Gazzette pipeline and still get the error. 
`Error: An unexpected error occurred during training. Error: string indices must be integers`

Working on a fresh Botfront install and following the conversation builder tutorial [here](https://botfront.io/docs/rasa/conversation-builder/)

Installed on own VM following: https://botfront.io/docs/installation/server-cluster#single-server-installation-vm

**Comment by a7u7a** [comment]
This is the error I get when I watch the logs during training:
```
botfront-app | 2021-04-09T16:45:23.964Z [error] : Training project u4EqmpDoSoQxd84uY - 37206.83 ms user: 6tmFr4owP3wkd7C5S /imports/api/instances/instances.methods.js - rasa.train with {"projectId":"u4EqmpDoSoQxd84uY"}    error: Request failed with status code 500 at settle (/opt/bundle/bundle/programs/server/npm/node_modules/axios/lib/core/settle.js:17:12)

**Comment by brandaobrandisborges** [comment]
@a7u7a share your NLU pipeline

**Comment by a7u7a** [comment]
```
pipeline:
  - name: WhitespaceTokenizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 200
  #- name: rasa_addons.nlu.components.gazette.Gazette
  - name: >-
      rasa_addons.nlu.components.intent_ranking_canonical_example_injector.IntentRankingCanonicalExampleInjector
  - name: EntitySynonymMapper
```

**Comment by a7u7a** [comment]
I have attempted several times to follow the example by running on a VM with  Ubuntu 20.04.2 LTS (unfortunately, I am not able to run on my own machine because of unrelated reasons) Attempts include fresh reinstall of all the toolchain. Please help

**Comment by Data-Hero** [comment]
I have the same  `Error: An unexpected error occurred during training. Error: string indices must be integers `Problem on a 20.04.2 LTS  (no VM)

**Comment by brandaobrandisborges** [comment]
That's strange, @a7u7a.
Extract the rasa project and confirm wether the changes have been applied.
My pipeline is identical to yours.

**Comment by V1faru** [comment]
@a7u7a did u manage to fix it. i am gettin the same exact error as you. tried the pipeline as well. followed the same instructions from the docs as well. trying to run it on a digital ocean ubuntu droplet.

**Comment by a7u7a** [comment]
Hi @V1faru @brandaobrandisborges no developments yet. Will see if I can take a look later today. Thanks!

**Comment by brandaobrandisborges** [comment]
> I have the same `Error: An unexpected error occurred during training. Error: string indices must be integers `Problem on a 20.04.2 LTS (no VM)

Have you tried removing the Gazette as said above? It has solved for me.

**Comment by coderon98** [comment]
> Hi! I also commented out Gazzette pipeline and still get the error.
> `Error: An unexpected error occurred during training. Error: string indices must be integers`
> 
> Working on a fresh Botfront install and following the conversation builder tutorial [here](https://botfront.io/docs/rasa/conversation-builder/)
> 
> Installed on own VM following: https://botfront.io/docs/installation/server-cluster#single-server-installation-vm

Hi, removing Gazette pipeline worked for me too ?
be aware that it is possible to do the configuration in two different places.

In admin> settings> Default NLU pipeline, this is the default configuration.

In project> NLU> Settings, this configuration takes priority during training.

**Comment by bsbarkur** [comment]
The above problem is solved by disabling the gazette in the pipeline. However, I'm facing one more problem now.

The bot utterance is not displayed and the utterance ID is shown in the chat widget. Why so ?

![image](https://user-images.githubusercontent.com/106684/115498850-ea4cfd00-a28b-11eb-8c27-7f671bc34801.png)

**Comment by coderon98** [comment]
> The above problem is solved by disabling the gazette in the pipeline. However, I'm facing one more problem now.
> 
> The bot utterance is not displayed and the utterance ID is shown in the chat widget. Why so ?
> 
> ![image](https://user-images.githubusercontent.com/106684/115498850-ea4cfd00-a28b-11eb-8c27-7f671bc34801.png)

I ran into the same problem. You have to edit utter_UujdPaGmf in the Responses tab, then redo a training session.
Then you have to refresh the conversation bubble

**Comment by brandaobrandisborges** [comment]
I've had the same problem as @bsbarkur and @coderon98; indeed renaming the response name works for the time being.

**Comment by bsbarkur** [comment]
tried. didn't work at all.

**Comment by a7u7a** [comment]
> > Hi! I also commented out Gazzette pipeline and still get the error.
> > `Error: An unexpected error occurred during training. Error: string indices must be integers`
> > Working on a fresh Botfront install and following the conversation builder tutorial [here](https://botfront.io/docs/rasa/conversation-builder/)
> > Installed on own VM following: https://botfront.io/docs/installation/server-cluster#single-server-installation-vm
> 
> Hi, removing Gazette pipeline worked for me too ?
> be aware that it is possible to do the configuration in two different places.
> 
> In admin> settings> Default NLU pipeline, this is the default configuration.
> 
> In project> NLU> Settings, this configuration takes priority during training.

Ok so I gave it a try again. I had no idea there was a Settings tab on the NLU panel. Commenting out the gazette line in this panel solved the issue. Thanks @coderon98

**Comment by brandaobrandisborges** [comment]
> tried. didn't work at all.

Well, after I rename and train, it works.
Make sure the train is successfull and the latest model is saved in your models, it may be using the older model.
