### ISSUE TITLE
Botfront does not support followup key word?

### ISSUE THREAD

**Issue by nhha1602** [botfront/botfront#999]
Hi,

I'm having an issue when I write stories:
I get notification: "bad line" when my stories has line: - followup{"name":"action_abc"}

Could you please help to show how to fix this?

**Comment by brandaobrandisborges** [comment]
Can you share the storie? Have you checked if the yaml is valid? I use this: https://yamlchecker.com/

**Comment by nhha1602** [comment]
Hi,

A part of my stories as below:

## int_change_permission_error/int_change_permission_more/int_change_permission_procedure/int_change_permission_form/int_change_permission_authoriser/int_change_permission_subject/int_change_permission_who_incharge
* int_change_permission_error OR int_change_permission_more OR int_change_permission_procedure OR int_change_permission_form OR int_change_permission_authoriser OR int_change_permission_subject OR int_change_permission_who_incharge
- action_change_permission
- followup{"name": "action_form_system_confirm"}
- action_form_system_confirm
- form{"name": "action_form_system_confirm"}
- form{"name": null}
- followup{"name": "action_change_permission"}
- action_change_permission
